// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: google/ads/googleads/v20/enums/access_reason.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing possible access reasons.
type AccessReasonEnum_AccessReason int32

const (
	// Not specified.
	AccessReasonEnum_UNSPECIFIED AccessReasonEnum_AccessReason = 0
	// Used for return value only. Represents value unknown in this version.
	AccessReasonEnum_UNKNOWN AccessReasonEnum_AccessReason = 1
	// The resource is owned by the user.
	AccessReasonEnum_OWNED AccessReasonEnum_AccessReason = 2
	// The resource is shared to the user.
	AccessReasonEnum_SHARED AccessReasonEnum_AccessReason = 3
	// The resource is licensed to the user.
	AccessReasonEnum_LICENSED AccessReasonEnum_AccessReason = 4
	// The user subscribed to the resource.
	AccessReasonEnum_SUBSCRIBED AccessReasonEnum_AccessReason = 5
	// The resource is accessible to the user.
	AccessReasonEnum_AFFILIATED AccessReasonEnum_AccessReason = 6
)

// Enum value maps for AccessReasonEnum_AccessReason.
var (
	AccessReasonEnum_AccessReason_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "OWNED",
		3: "SHARED",
		4: "LICENSED",
		5: "SUBSCRIBED",
		6: "AFFILIATED",
	}
	AccessReasonEnum_AccessReason_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UNKNOWN":     1,
		"OWNED":       2,
		"SHARED":      3,
		"LICENSED":    4,
		"SUBSCRIBED":  5,
		"AFFILIATED":  6,
	}
)

func (x AccessReasonEnum_AccessReason) Enum() *AccessReasonEnum_AccessReason {
	p := new(AccessReasonEnum_AccessReason)
	*p = x
	return p
}

func (x AccessReasonEnum_AccessReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessReasonEnum_AccessReason) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v20_enums_access_reason_proto_enumTypes[0].Descriptor()
}

func (AccessReasonEnum_AccessReason) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v20_enums_access_reason_proto_enumTypes[0]
}

func (x AccessReasonEnum_AccessReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessReasonEnum_AccessReason.Descriptor instead.
func (AccessReasonEnum_AccessReason) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_enums_access_reason_proto_rawDescGZIP(), []int{0, 0}
}

// Indicates the way the resource such as user list is related to a user.
type AccessReasonEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessReasonEnum) Reset() {
	*x = AccessReasonEnum{}
	mi := &file_google_ads_googleads_v20_enums_access_reason_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessReasonEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessReasonEnum) ProtoMessage() {}

func (x *AccessReasonEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_enums_access_reason_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessReasonEnum.ProtoReflect.Descriptor instead.
func (*AccessReasonEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_enums_access_reason_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v20_enums_access_reason_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v20_enums_access_reason_proto_rawDesc = "" +
	"\n" +
	"2google/ads/googleads/v20/enums/access_reason.proto\x12\x1egoogle.ads.googleads.v20.enums\"\x85\x01\n" +
	"\x10AccessReasonEnum\"q\n" +
	"\fAccessReason\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\t\n" +
	"\x05OWNED\x10\x02\x12\n" +
	"\n" +
	"\x06SHARED\x10\x03\x12\f\n" +
	"\bLICENSED\x10\x04\x12\x0e\n" +
	"\n" +
	"SUBSCRIBED\x10\x05\x12\x0e\n" +
	"\n" +
	"AFFILIATED\x10\x06B\xeb\x01\n" +
	"\"com.google.ads.googleads.v20.enumsB\x11AccessReasonProtoP\x01ZCgithub.com/shenzhencenter/google-ads-pb/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V20.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V20\\Enums\xea\x02\"Google::Ads::GoogleAds::V20::Enumsb\x06proto3"

var (
	file_google_ads_googleads_v20_enums_access_reason_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v20_enums_access_reason_proto_rawDescData []byte
)

func file_google_ads_googleads_v20_enums_access_reason_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v20_enums_access_reason_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v20_enums_access_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_enums_access_reason_proto_rawDesc), len(file_google_ads_googleads_v20_enums_access_reason_proto_rawDesc)))
	})
	return file_google_ads_googleads_v20_enums_access_reason_proto_rawDescData
}

var file_google_ads_googleads_v20_enums_access_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v20_enums_access_reason_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v20_enums_access_reason_proto_goTypes = []any{
	(AccessReasonEnum_AccessReason)(0), // 0: google.ads.googleads.v20.enums.AccessReasonEnum.AccessReason
	(*AccessReasonEnum)(nil),           // 1: google.ads.googleads.v20.enums.AccessReasonEnum
}
var file_google_ads_googleads_v20_enums_access_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v20_enums_access_reason_proto_init() }
func file_google_ads_googleads_v20_enums_access_reason_proto_init() {
	if File_google_ads_googleads_v20_enums_access_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_enums_access_reason_proto_rawDesc), len(file_google_ads_googleads_v20_enums_access_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v20_enums_access_reason_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v20_enums_access_reason_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v20_enums_access_reason_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v20_enums_access_reason_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v20_enums_access_reason_proto = out.File
	file_google_ads_googleads_v20_enums_access_reason_proto_goTypes = nil
	file_google_ads_googleads_v20_enums_access_reason_proto_depIdxs = nil
}
