// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.4
// source: google/ads/googleads/v23/enums/asset_orientation.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The orientation of an image or video asset.
type AssetOrientationEnum_AssetOrientation int32

const (
	// Not specified.
	AssetOrientationEnum_UNSPECIFIED AssetOrientationEnum_AssetOrientation = 0
	// The value is unknown in this version.
	AssetOrientationEnum_UNKNOWN AssetOrientationEnum_AssetOrientation = 1
	// Landscape orientation.
	AssetOrientationEnum_LANDSCAPE AssetOrientationEnum_AssetOrientation = 2
	// Portrait orientation.
	AssetOrientationEnum_PORTRAIT AssetOrientationEnum_AssetOrientation = 3
	// Square orientation.
	AssetOrientationEnum_SQUARE AssetOrientationEnum_AssetOrientation = 4
)

// Enum value maps for AssetOrientationEnum_AssetOrientation.
var (
	AssetOrientationEnum_AssetOrientation_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "LANDSCAPE",
		3: "PORTRAIT",
		4: "SQUARE",
	}
	AssetOrientationEnum_AssetOrientation_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UNKNOWN":     1,
		"LANDSCAPE":   2,
		"PORTRAIT":    3,
		"SQUARE":      4,
	}
)

func (x AssetOrientationEnum_AssetOrientation) Enum() *AssetOrientationEnum_AssetOrientation {
	p := new(AssetOrientationEnum_AssetOrientation)
	*p = x
	return p
}

func (x AssetOrientationEnum_AssetOrientation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetOrientationEnum_AssetOrientation) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v23_enums_asset_orientation_proto_enumTypes[0].Descriptor()
}

func (AssetOrientationEnum_AssetOrientation) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v23_enums_asset_orientation_proto_enumTypes[0]
}

func (x AssetOrientationEnum_AssetOrientation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetOrientationEnum_AssetOrientation.Descriptor instead.
func (AssetOrientationEnum_AssetOrientation) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing the orientation of an image or video asset.
type AssetOrientationEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetOrientationEnum) Reset() {
	*x = AssetOrientationEnum{}
	mi := &file_google_ads_googleads_v23_enums_asset_orientation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetOrientationEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetOrientationEnum) ProtoMessage() {}

func (x *AssetOrientationEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v23_enums_asset_orientation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetOrientationEnum.ProtoReflect.Descriptor instead.
func (*AssetOrientationEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v23_enums_asset_orientation_proto protoreflect.FileDescriptor

var file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDesc = string([]byte{
	0x0a, 0x36, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x61, 0x64, 0x73, 0x2f, 0x76, 0x32, 0x33, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73,
	0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x61, 0x64, 0x73, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x64, 0x73, 0x2e, 0x76,
	0x32, 0x33, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x22, 0x71, 0x0a, 0x14, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x75, 0x6d,
	0x22, 0x59, 0x0a, 0x10, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x41, 0x4e, 0x44, 0x53, 0x43, 0x41, 0x50, 0x45, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x4f, 0x52, 0x54, 0x52, 0x41, 0x49, 0x54, 0x10, 0x03, 0x12,
	0x0a, 0x0a, 0x06, 0x53, 0x51, 0x55, 0x41, 0x52, 0x45, 0x10, 0x04, 0x42, 0xef, 0x01, 0x0a, 0x22,
	0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x32, 0x33, 0x2e, 0x65, 0x6e, 0x75,
	0x6d, 0x73, 0x42, 0x15, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x43, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x70,
	0x69, 0x73, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x64, 0x73,
	0x2f, 0x76, 0x32, 0x33, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x3b, 0x65, 0x6e, 0x75, 0x6d, 0x73,
	0xa2, 0x02, 0x03, 0x47, 0x41, 0x41, 0xaa, 0x02, 0x1e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x41, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x41, 0x64, 0x73, 0x2e, 0x56, 0x32,
	0x33, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x73, 0xca, 0x02, 0x1e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x5c, 0x41, 0x64, 0x73, 0x5c, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x41, 0x64, 0x73, 0x5c, 0x56,
	0x32, 0x33, 0x5c, 0x45, 0x6e, 0x75, 0x6d, 0x73, 0xea, 0x02, 0x22, 0x47, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x3a, 0x3a, 0x41, 0x64, 0x73, 0x3a, 0x3a, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x41, 0x64,
	0x73, 0x3a, 0x3a, 0x56, 0x32, 0x33, 0x3a, 0x3a, 0x45, 0x6e, 0x75, 0x6d, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDescData []byte
)

func file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDesc), len(file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDesc)))
	})
	return file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDescData
}

var file_google_ads_googleads_v23_enums_asset_orientation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v23_enums_asset_orientation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v23_enums_asset_orientation_proto_goTypes = []any{
	(AssetOrientationEnum_AssetOrientation)(0), // 0: google.ads.googleads.v23.enums.AssetOrientationEnum.AssetOrientation
	(*AssetOrientationEnum)(nil),               // 1: google.ads.googleads.v23.enums.AssetOrientationEnum
}
var file_google_ads_googleads_v23_enums_asset_orientation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v23_enums_asset_orientation_proto_init() }
func file_google_ads_googleads_v23_enums_asset_orientation_proto_init() {
	if File_google_ads_googleads_v23_enums_asset_orientation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDesc), len(file_google_ads_googleads_v23_enums_asset_orientation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v23_enums_asset_orientation_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v23_enums_asset_orientation_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v23_enums_asset_orientation_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v23_enums_asset_orientation_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v23_enums_asset_orientation_proto = out.File
	file_google_ads_googleads_v23_enums_asset_orientation_proto_goTypes = nil
	file_google_ads_googleads_v23_enums_asset_orientation_proto_depIdxs = nil
}
