// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: google/ads/googleads/v19/enums/keyword_plan_competition_level.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Competition level of a keyword.
type KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel int32

const (
	// Not specified.
	KeywordPlanCompetitionLevelEnum_UNSPECIFIED KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel = 0
	// The value is unknown in this version.
	KeywordPlanCompetitionLevelEnum_UNKNOWN KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel = 1
	// Low competition. The Competition Index range for this is [0, 33].
	KeywordPlanCompetitionLevelEnum_LOW KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel = 2
	// Medium competition. The Competition Index range for this is [34, 66].
	KeywordPlanCompetitionLevelEnum_MEDIUM KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel = 3
	// High competition. The Competition Index range for this is [67, 100].
	KeywordPlanCompetitionLevelEnum_HIGH KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel = 4
)

// Enum value maps for KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel.
var (
	KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "LOW",
		3: "MEDIUM",
		4: "HIGH",
	}
	KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UNKNOWN":     1,
		"LOW":         2,
		"MEDIUM":      3,
		"HIGH":        4,
	}
)

func (x KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel) Enum() *KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel {
	p := new(KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel)
	*p = x
	return p
}

func (x KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_enumTypes[0].Descriptor()
}

func (KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_enumTypes[0]
}

func (x KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel.Descriptor instead.
func (KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enumeration of keyword competition levels. The competition
// level indicates how competitive ad placement is for a keyword and
// is determined by the number of advertisers bidding on that keyword relative
// to all keywords across Google. The competition level can depend on the
// location and Search Network targeting options you've selected.
type KeywordPlanCompetitionLevelEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeywordPlanCompetitionLevelEnum) Reset() {
	*x = KeywordPlanCompetitionLevelEnum{}
	mi := &file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordPlanCompetitionLevelEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordPlanCompetitionLevelEnum) ProtoMessage() {}

func (x *KeywordPlanCompetitionLevelEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordPlanCompetitionLevelEnum.ProtoReflect.Descriptor instead.
func (*KeywordPlanCompetitionLevelEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDesc = "" +
	"\n" +
	"Cgoogle/ads/googleads/v19/enums/keyword_plan_competition_level.proto\x12\x1egoogle.ads.googleads.v19.enums\"}\n" +
	"\x1fKeywordPlanCompetitionLevelEnum\"Z\n" +
	"\x1bKeywordPlanCompetitionLevel\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\a\n" +
	"\x03LOW\x10\x02\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x03\x12\b\n" +
	"\x04HIGH\x10\x04B\xfa\x01\n" +
	"\"com.google.ads.googleads.v19.enumsB KeywordPlanCompetitionLevelProtoP\x01ZCgithub.com/shenzhencenter/google-ads-pb/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V19.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V19\\Enums\xea\x02\"Google::Ads::GoogleAds::V19::Enumsb\x06proto3"

var (
	file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDescData []byte
)

func file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDesc), len(file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDesc)))
	})
	return file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDescData
}

var file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_goTypes = []any{
	(KeywordPlanCompetitionLevelEnum_KeywordPlanCompetitionLevel)(0), // 0: google.ads.googleads.v19.enums.KeywordPlanCompetitionLevelEnum.KeywordPlanCompetitionLevel
	(*KeywordPlanCompetitionLevelEnum)(nil),                          // 1: google.ads.googleads.v19.enums.KeywordPlanCompetitionLevelEnum
}
var file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_init() }
func file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_init() {
	if File_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDesc), len(file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto = out.File
	file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_goTypes = nil
	file_google_ads_googleads_v19_enums_keyword_plan_competition_level_proto_depIdxs = nil
}
