// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: google/ads/googleads/v19/resources/campaign_asset.proto

package resources

import (
	common "github.com/shenzhencenter/google-ads-pb/common"
	enums "github.com/shenzhencenter/google-ads-pb/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A link between a Campaign and an Asset.
type CampaignAsset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Immutable. The resource name of the campaign asset.
	// CampaignAsset resource names have the form:
	//
	// `customers/{customer_id}/campaignAssets/{campaign_id}~{asset_id}~{field_type}`
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Immutable. The campaign to which the asset is linked.
	Campaign *string `protobuf:"bytes,6,opt,name=campaign,proto3,oneof" json:"campaign,omitempty"`
	// Immutable. The asset which is linked to the campaign.
	Asset *string `protobuf:"bytes,7,opt,name=asset,proto3,oneof" json:"asset,omitempty"`
	// Immutable. Role that the asset takes under the linked campaign.
	// Required.
	FieldType enums.AssetFieldTypeEnum_AssetFieldType `protobuf:"varint,4,opt,name=field_type,json=fieldType,proto3,enum=google.ads.googleads.v19.enums.AssetFieldTypeEnum_AssetFieldType" json:"field_type,omitempty"`
	// Output only. Source of the campaign asset link.
	Source enums.AssetSourceEnum_AssetSource `protobuf:"varint,8,opt,name=source,proto3,enum=google.ads.googleads.v19.enums.AssetSourceEnum_AssetSource" json:"source,omitempty"`
	// Status of the campaign asset.
	Status enums.AssetLinkStatusEnum_AssetLinkStatus `protobuf:"varint,5,opt,name=status,proto3,enum=google.ads.googleads.v19.enums.AssetLinkStatusEnum_AssetLinkStatus" json:"status,omitempty"`
	// Output only. Provides the PrimaryStatus of this asset link.
	// Primary status is meant essentially to differentiate between the plain
	// "status" field, which has advertiser set values of enabled, paused, or
	// removed.  The primary status takes into account other signals (for assets
	// its mainly policy and quality approvals) to come up with a more
	// comprehensive status to indicate its serving state.
	PrimaryStatus enums.AssetLinkPrimaryStatusEnum_AssetLinkPrimaryStatus `protobuf:"varint,9,opt,name=primary_status,json=primaryStatus,proto3,enum=google.ads.googleads.v19.enums.AssetLinkPrimaryStatusEnum_AssetLinkPrimaryStatus" json:"primary_status,omitempty"`
	// Output only. Provides the details of the primary status and its associated
	// reasons.
	PrimaryStatusDetails []*common.AssetLinkPrimaryStatusDetails `protobuf:"bytes,10,rep,name=primary_status_details,json=primaryStatusDetails,proto3" json:"primary_status_details,omitempty"`
	// Output only. Provides a list of reasons for why an asset is not serving or
	// not serving at full capacity.
	PrimaryStatusReasons []enums.AssetLinkPrimaryStatusReasonEnum_AssetLinkPrimaryStatusReason `protobuf:"varint,11,rep,packed,name=primary_status_reasons,json=primaryStatusReasons,proto3,enum=google.ads.googleads.v19.enums.AssetLinkPrimaryStatusReasonEnum_AssetLinkPrimaryStatusReason" json:"primary_status_reasons,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CampaignAsset) Reset() {
	*x = CampaignAsset{}
	mi := &file_google_ads_googleads_v19_resources_campaign_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignAsset) ProtoMessage() {}

func (x *CampaignAsset) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v19_resources_campaign_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignAsset.ProtoReflect.Descriptor instead.
func (*CampaignAsset) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDescGZIP(), []int{0}
}

func (x *CampaignAsset) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *CampaignAsset) GetCampaign() string {
	if x != nil && x.Campaign != nil {
		return *x.Campaign
	}
	return ""
}

func (x *CampaignAsset) GetAsset() string {
	if x != nil && x.Asset != nil {
		return *x.Asset
	}
	return ""
}

func (x *CampaignAsset) GetFieldType() enums.AssetFieldTypeEnum_AssetFieldType {
	if x != nil {
		return x.FieldType
	}
	return enums.AssetFieldTypeEnum_AssetFieldType(0)
}

func (x *CampaignAsset) GetSource() enums.AssetSourceEnum_AssetSource {
	if x != nil {
		return x.Source
	}
	return enums.AssetSourceEnum_AssetSource(0)
}

func (x *CampaignAsset) GetStatus() enums.AssetLinkStatusEnum_AssetLinkStatus {
	if x != nil {
		return x.Status
	}
	return enums.AssetLinkStatusEnum_AssetLinkStatus(0)
}

func (x *CampaignAsset) GetPrimaryStatus() enums.AssetLinkPrimaryStatusEnum_AssetLinkPrimaryStatus {
	if x != nil {
		return x.PrimaryStatus
	}
	return enums.AssetLinkPrimaryStatusEnum_AssetLinkPrimaryStatus(0)
}

func (x *CampaignAsset) GetPrimaryStatusDetails() []*common.AssetLinkPrimaryStatusDetails {
	if x != nil {
		return x.PrimaryStatusDetails
	}
	return nil
}

func (x *CampaignAsset) GetPrimaryStatusReasons() []enums.AssetLinkPrimaryStatusReasonEnum_AssetLinkPrimaryStatusReason {
	if x != nil {
		return x.PrimaryStatusReasons
	}
	return nil
}

var File_google_ads_googleads_v19_resources_campaign_asset_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDesc = "" +
	"\n" +
	"7google/ads/googleads/v19/resources/campaign_asset.proto\x12\"google.ads.googleads.v19.resources\x1a2google/ads/googleads/v19/common/asset_policy.proto\x1a5google/ads/googleads/v19/enums/asset_field_type.proto\x1a>google/ads/googleads/v19/enums/asset_link_primary_status.proto\x1aEgoogle/ads/googleads/v19/enums/asset_link_primary_status_reason.proto\x1a6google/ads/googleads/v19/enums/asset_link_status.proto\x1a1google/ads/googleads/v19/enums/asset_source.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xb8\b\n" +
	"\rCampaignAsset\x12S\n" +
	"\rresource_name\x18\x01 \x01(\tB.\xe0A\x05\xfaA(\n" +
	"&googleads.googleapis.com/CampaignAssetR\fresourceName\x12J\n" +
	"\bcampaign\x18\x06 \x01(\tB)\xe0A\x05\xfaA#\n" +
	"!googleads.googleapis.com/CampaignH\x00R\bcampaign\x88\x01\x01\x12A\n" +
	"\x05asset\x18\a \x01(\tB&\xe0A\x05\xfaA \n" +
	"\x1egoogleads.googleapis.com/AssetH\x01R\x05asset\x88\x01\x01\x12e\n" +
	"\n" +
	"field_type\x18\x04 \x01(\x0e2A.google.ads.googleads.v19.enums.AssetFieldTypeEnum.AssetFieldTypeB\x03\xe0A\x05R\tfieldType\x12X\n" +
	"\x06source\x18\b \x01(\x0e2;.google.ads.googleads.v19.enums.AssetSourceEnum.AssetSourceB\x03\xe0A\x03R\x06source\x12[\n" +
	"\x06status\x18\x05 \x01(\x0e2C.google.ads.googleads.v19.enums.AssetLinkStatusEnum.AssetLinkStatusR\x06status\x12}\n" +
	"\x0eprimary_status\x18\t \x01(\x0e2Q.google.ads.googleads.v19.enums.AssetLinkPrimaryStatusEnum.AssetLinkPrimaryStatusB\x03\xe0A\x03R\rprimaryStatus\x12y\n" +
	"\x16primary_status_details\x18\n" +
	" \x03(\v2>.google.ads.googleads.v19.common.AssetLinkPrimaryStatusDetailsB\x03\xe0A\x03R\x14primaryStatusDetails\x12\x98\x01\n" +
	"\x16primary_status_reasons\x18\v \x03(\x0e2].google.ads.googleads.v19.enums.AssetLinkPrimaryStatusReasonEnum.AssetLinkPrimaryStatusReasonB\x03\xe0A\x03R\x14primaryStatusReasons:y\xeaAv\n" +
	"&googleads.googleapis.com/CampaignAsset\x12Lcustomers/{customer_id}/campaignAssets/{campaign_id}~{asset_id}~{field_type}B\v\n" +
	"\t_campaignB\b\n" +
	"\x06_assetB\x84\x02\n" +
	"&com.google.ads.googleads.v19.resourcesB\x12CampaignAssetProtoP\x01ZKgithub.com/shenzhencenter/google-ads-pb/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V19.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V19\\Resources\xea\x02&Google::Ads::GoogleAds::V19::Resourcesb\x06proto3"

var (
	file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDescData []byte
)

func file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDesc), len(file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDesc)))
	})
	return file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDescData
}

var file_google_ads_googleads_v19_resources_campaign_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v19_resources_campaign_asset_proto_goTypes = []any{
	(*CampaignAsset)(nil),                                                    // 0: google.ads.googleads.v19.resources.CampaignAsset
	(enums.AssetFieldTypeEnum_AssetFieldType)(0),                             // 1: google.ads.googleads.v19.enums.AssetFieldTypeEnum.AssetFieldType
	(enums.AssetSourceEnum_AssetSource)(0),                                   // 2: google.ads.googleads.v19.enums.AssetSourceEnum.AssetSource
	(enums.AssetLinkStatusEnum_AssetLinkStatus)(0),                           // 3: google.ads.googleads.v19.enums.AssetLinkStatusEnum.AssetLinkStatus
	(enums.AssetLinkPrimaryStatusEnum_AssetLinkPrimaryStatus)(0),             // 4: google.ads.googleads.v19.enums.AssetLinkPrimaryStatusEnum.AssetLinkPrimaryStatus
	(*common.AssetLinkPrimaryStatusDetails)(nil),                             // 5: google.ads.googleads.v19.common.AssetLinkPrimaryStatusDetails
	(enums.AssetLinkPrimaryStatusReasonEnum_AssetLinkPrimaryStatusReason)(0), // 6: google.ads.googleads.v19.enums.AssetLinkPrimaryStatusReasonEnum.AssetLinkPrimaryStatusReason
}
var file_google_ads_googleads_v19_resources_campaign_asset_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v19.resources.CampaignAsset.field_type:type_name -> google.ads.googleads.v19.enums.AssetFieldTypeEnum.AssetFieldType
	2, // 1: google.ads.googleads.v19.resources.CampaignAsset.source:type_name -> google.ads.googleads.v19.enums.AssetSourceEnum.AssetSource
	3, // 2: google.ads.googleads.v19.resources.CampaignAsset.status:type_name -> google.ads.googleads.v19.enums.AssetLinkStatusEnum.AssetLinkStatus
	4, // 3: google.ads.googleads.v19.resources.CampaignAsset.primary_status:type_name -> google.ads.googleads.v19.enums.AssetLinkPrimaryStatusEnum.AssetLinkPrimaryStatus
	5, // 4: google.ads.googleads.v19.resources.CampaignAsset.primary_status_details:type_name -> google.ads.googleads.v19.common.AssetLinkPrimaryStatusDetails
	6, // 5: google.ads.googleads.v19.resources.CampaignAsset.primary_status_reasons:type_name -> google.ads.googleads.v19.enums.AssetLinkPrimaryStatusReasonEnum.AssetLinkPrimaryStatusReason
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v19_resources_campaign_asset_proto_init() }
func file_google_ads_googleads_v19_resources_campaign_asset_proto_init() {
	if File_google_ads_googleads_v19_resources_campaign_asset_proto != nil {
		return
	}
	file_google_ads_googleads_v19_resources_campaign_asset_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDesc), len(file_google_ads_googleads_v19_resources_campaign_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v19_resources_campaign_asset_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v19_resources_campaign_asset_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v19_resources_campaign_asset_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v19_resources_campaign_asset_proto = out.File
	file_google_ads_googleads_v19_resources_campaign_asset_proto_goTypes = nil
	file_google_ads_googleads_v19_resources_campaign_asset_proto_depIdxs = nil
}
