// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: google/ads/googleads/v19/resources/custom_interest.proto

package resources

import (
	enums "github.com/shenzhencenter/google-ads-pb/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A custom interest. This is a list of users by interest.
type CustomInterest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Immutable. The resource name of the custom interest.
	// Custom interest resource names have the form:
	//
	// `customers/{customer_id}/customInterests/{custom_interest_id}`
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Output only. Id of the custom interest.
	Id *int64 `protobuf:"varint,8,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Status of this custom interest. Indicates whether the custom interest is
	// enabled or removed.
	Status enums.CustomInterestStatusEnum_CustomInterestStatus `protobuf:"varint,3,opt,name=status,proto3,enum=google.ads.googleads.v19.enums.CustomInterestStatusEnum_CustomInterestStatus" json:"status,omitempty"`
	// Name of the custom interest. It should be unique across the same custom
	// affinity audience.
	// This field is required for create operations.
	Name *string `protobuf:"bytes,9,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Type of the custom interest, CUSTOM_AFFINITY or CUSTOM_INTENT.
	// By default the type is set to CUSTOM_AFFINITY.
	Type enums.CustomInterestTypeEnum_CustomInterestType `protobuf:"varint,5,opt,name=type,proto3,enum=google.ads.googleads.v19.enums.CustomInterestTypeEnum_CustomInterestType" json:"type,omitempty"`
	// Description of this custom interest audience.
	Description *string `protobuf:"bytes,10,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// List of custom interest members that this custom interest is composed of.
	// Members can be added during CustomInterest creation. If members are
	// presented in UPDATE operation, existing members will be overridden.
	Members       []*CustomInterestMember `protobuf:"bytes,7,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomInterest) Reset() {
	*x = CustomInterest{}
	mi := &file_google_ads_googleads_v19_resources_custom_interest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomInterest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomInterest) ProtoMessage() {}

func (x *CustomInterest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v19_resources_custom_interest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomInterest.ProtoReflect.Descriptor instead.
func (*CustomInterest) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v19_resources_custom_interest_proto_rawDescGZIP(), []int{0}
}

func (x *CustomInterest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *CustomInterest) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *CustomInterest) GetStatus() enums.CustomInterestStatusEnum_CustomInterestStatus {
	if x != nil {
		return x.Status
	}
	return enums.CustomInterestStatusEnum_CustomInterestStatus(0)
}

func (x *CustomInterest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CustomInterest) GetType() enums.CustomInterestTypeEnum_CustomInterestType {
	if x != nil {
		return x.Type
	}
	return enums.CustomInterestTypeEnum_CustomInterestType(0)
}

func (x *CustomInterest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CustomInterest) GetMembers() []*CustomInterestMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// A member of custom interest audience. A member can be a keyword or url.
// It is immutable, that is, it can only be created or removed but not changed.
type CustomInterestMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of custom interest member, KEYWORD or URL.
	MemberType enums.CustomInterestMemberTypeEnum_CustomInterestMemberType `protobuf:"varint,1,opt,name=member_type,json=memberType,proto3,enum=google.ads.googleads.v19.enums.CustomInterestMemberTypeEnum_CustomInterestMemberType" json:"member_type,omitempty"`
	// Keyword text when member_type is KEYWORD or URL string when
	// member_type is URL.
	Parameter     *string `protobuf:"bytes,3,opt,name=parameter,proto3,oneof" json:"parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomInterestMember) Reset() {
	*x = CustomInterestMember{}
	mi := &file_google_ads_googleads_v19_resources_custom_interest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomInterestMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomInterestMember) ProtoMessage() {}

func (x *CustomInterestMember) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v19_resources_custom_interest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomInterestMember.ProtoReflect.Descriptor instead.
func (*CustomInterestMember) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v19_resources_custom_interest_proto_rawDescGZIP(), []int{1}
}

func (x *CustomInterestMember) GetMemberType() enums.CustomInterestMemberTypeEnum_CustomInterestMemberType {
	if x != nil {
		return x.MemberType
	}
	return enums.CustomInterestMemberTypeEnum_CustomInterestMemberType(0)
}

func (x *CustomInterestMember) GetParameter() string {
	if x != nil && x.Parameter != nil {
		return *x.Parameter
	}
	return ""
}

var File_google_ads_googleads_v19_resources_custom_interest_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v19_resources_custom_interest_proto_rawDesc = "" +
	"\n" +
	"8google/ads/googleads/v19/resources/custom_interest.proto\x12\"google.ads.googleads.v19.resources\x1a@google/ads/googleads/v19/enums/custom_interest_member_type.proto\x1a;google/ads/googleads/v19/enums/custom_interest_status.proto\x1a9google/ads/googleads/v19/enums/custom_interest_type.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xe6\x04\n" +
	"\x0eCustomInterest\x12T\n" +
	"\rresource_name\x18\x01 \x01(\tB/\xe0A\x05\xfaA)\n" +
	"'googleads.googleapis.com/CustomInterestR\fresourceName\x12\x18\n" +
	"\x02id\x18\b \x01(\x03B\x03\xe0A\x03H\x00R\x02id\x88\x01\x01\x12e\n" +
	"\x06status\x18\x03 \x01(\x0e2M.google.ads.googleads.v19.enums.CustomInterestStatusEnum.CustomInterestStatusR\x06status\x12\x17\n" +
	"\x04name\x18\t \x01(\tH\x01R\x04name\x88\x01\x01\x12]\n" +
	"\x04type\x18\x05 \x01(\x0e2I.google.ads.googleads.v19.enums.CustomInterestTypeEnum.CustomInterestTypeR\x04type\x12%\n" +
	"\vdescription\x18\n" +
	" \x01(\tH\x02R\vdescription\x88\x01\x01\x12R\n" +
	"\amembers\x18\a \x03(\v28.google.ads.googleads.v19.resources.CustomInterestMemberR\amembers:j\xeaAg\n" +
	"'googleads.googleapis.com/CustomInterest\x12<customers/{customer_id}/customInterests/{custom_interest_id}B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"\xbf\x01\n" +
	"\x14CustomInterestMember\x12v\n" +
	"\vmember_type\x18\x01 \x01(\x0e2U.google.ads.googleads.v19.enums.CustomInterestMemberTypeEnum.CustomInterestMemberTypeR\n" +
	"memberType\x12!\n" +
	"\tparameter\x18\x03 \x01(\tH\x00R\tparameter\x88\x01\x01B\f\n" +
	"\n" +
	"_parameterB\x85\x02\n" +
	"&com.google.ads.googleads.v19.resourcesB\x13CustomInterestProtoP\x01ZKgithub.com/shenzhencenter/google-ads-pb/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V19.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V19\\Resources\xea\x02&Google::Ads::GoogleAds::V19::Resourcesb\x06proto3"

var (
	file_google_ads_googleads_v19_resources_custom_interest_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v19_resources_custom_interest_proto_rawDescData []byte
)

func file_google_ads_googleads_v19_resources_custom_interest_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v19_resources_custom_interest_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v19_resources_custom_interest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_resources_custom_interest_proto_rawDesc), len(file_google_ads_googleads_v19_resources_custom_interest_proto_rawDesc)))
	})
	return file_google_ads_googleads_v19_resources_custom_interest_proto_rawDescData
}

var file_google_ads_googleads_v19_resources_custom_interest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_google_ads_googleads_v19_resources_custom_interest_proto_goTypes = []any{
	(*CustomInterest)(nil),                                           // 0: google.ads.googleads.v19.resources.CustomInterest
	(*CustomInterestMember)(nil),                                     // 1: google.ads.googleads.v19.resources.CustomInterestMember
	(enums.CustomInterestStatusEnum_CustomInterestStatus)(0),         // 2: google.ads.googleads.v19.enums.CustomInterestStatusEnum.CustomInterestStatus
	(enums.CustomInterestTypeEnum_CustomInterestType)(0),             // 3: google.ads.googleads.v19.enums.CustomInterestTypeEnum.CustomInterestType
	(enums.CustomInterestMemberTypeEnum_CustomInterestMemberType)(0), // 4: google.ads.googleads.v19.enums.CustomInterestMemberTypeEnum.CustomInterestMemberType
}
var file_google_ads_googleads_v19_resources_custom_interest_proto_depIdxs = []int32{
	2, // 0: google.ads.googleads.v19.resources.CustomInterest.status:type_name -> google.ads.googleads.v19.enums.CustomInterestStatusEnum.CustomInterestStatus
	3, // 1: google.ads.googleads.v19.resources.CustomInterest.type:type_name -> google.ads.googleads.v19.enums.CustomInterestTypeEnum.CustomInterestType
	1, // 2: google.ads.googleads.v19.resources.CustomInterest.members:type_name -> google.ads.googleads.v19.resources.CustomInterestMember
	4, // 3: google.ads.googleads.v19.resources.CustomInterestMember.member_type:type_name -> google.ads.googleads.v19.enums.CustomInterestMemberTypeEnum.CustomInterestMemberType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v19_resources_custom_interest_proto_init() }
func file_google_ads_googleads_v19_resources_custom_interest_proto_init() {
	if File_google_ads_googleads_v19_resources_custom_interest_proto != nil {
		return
	}
	file_google_ads_googleads_v19_resources_custom_interest_proto_msgTypes[0].OneofWrappers = []any{}
	file_google_ads_googleads_v19_resources_custom_interest_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_resources_custom_interest_proto_rawDesc), len(file_google_ads_googleads_v19_resources_custom_interest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v19_resources_custom_interest_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v19_resources_custom_interest_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v19_resources_custom_interest_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v19_resources_custom_interest_proto = out.File
	file_google_ads_googleads_v19_resources_custom_interest_proto_goTypes = nil
	file_google_ads_googleads_v19_resources_custom_interest_proto_depIdxs = nil
}
