// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: google/ads/googleads/v19/resources/customer_asset_set.proto

package resources

import (
	enums "github.com/shenzhencenter/google-ads-pb/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CustomerAssetSet is the linkage between a customer and an asset set.
// Adding a CustomerAssetSet links an asset set with a customer.
type CustomerAssetSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Immutable. The resource name of the customer asset set.
	// Asset set asset resource names have the form:
	//
	// `customers/{customer_id}/customerAssetSets/{asset_set_id}`
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Immutable. The asset set which is linked to the customer.
	AssetSet string `protobuf:"bytes,2,opt,name=asset_set,json=assetSet,proto3" json:"asset_set,omitempty"`
	// Immutable. The customer to which this asset set is linked.
	Customer string `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	// Output only. The status of the customer asset set asset. Read-only.
	Status        enums.AssetSetLinkStatusEnum_AssetSetLinkStatus `protobuf:"varint,4,opt,name=status,proto3,enum=google.ads.googleads.v19.enums.AssetSetLinkStatusEnum_AssetSetLinkStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerAssetSet) Reset() {
	*x = CustomerAssetSet{}
	mi := &file_google_ads_googleads_v19_resources_customer_asset_set_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerAssetSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerAssetSet) ProtoMessage() {}

func (x *CustomerAssetSet) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v19_resources_customer_asset_set_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerAssetSet.ProtoReflect.Descriptor instead.
func (*CustomerAssetSet) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerAssetSet) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *CustomerAssetSet) GetAssetSet() string {
	if x != nil {
		return x.AssetSet
	}
	return ""
}

func (x *CustomerAssetSet) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *CustomerAssetSet) GetStatus() enums.AssetSetLinkStatusEnum_AssetSetLinkStatus {
	if x != nil {
		return x.Status
	}
	return enums.AssetSetLinkStatusEnum_AssetSetLinkStatus(0)
}

var File_google_ads_googleads_v19_resources_customer_asset_set_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDesc = "" +
	"\n" +
	";google/ads/googleads/v19/resources/customer_asset_set.proto\x12\"google.ads.googleads.v19.resources\x1a:google/ads/googleads/v19/enums/asset_set_link_status.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xcb\x03\n" +
	"\x10CustomerAssetSet\x12V\n" +
	"\rresource_name\x18\x01 \x01(\tB1\xe0A\x05\xfaA+\n" +
	")googleads.googleapis.com/CustomerAssetSetR\fresourceName\x12F\n" +
	"\tasset_set\x18\x02 \x01(\tB)\xe0A\x05\xfaA#\n" +
	"!googleads.googleapis.com/AssetSetR\bassetSet\x12E\n" +
	"\bcustomer\x18\x03 \x01(\tB)\xe0A\x05\xfaA#\n" +
	"!googleads.googleapis.com/CustomerR\bcustomer\x12f\n" +
	"\x06status\x18\x04 \x01(\x0e2I.google.ads.googleads.v19.enums.AssetSetLinkStatusEnum.AssetSetLinkStatusB\x03\xe0A\x03R\x06status:h\xeaAe\n" +
	")googleads.googleapis.com/CustomerAssetSet\x128customers/{customer_id}/customerAssetSets/{asset_set_id}B\x87\x02\n" +
	"&com.google.ads.googleads.v19.resourcesB\x15CustomerAssetSetProtoP\x01ZKgithub.com/shenzhencenter/google-ads-pb/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V19.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V19\\Resources\xea\x02&Google::Ads::GoogleAds::V19::Resourcesb\x06proto3"

var (
	file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDescData []byte
)

func file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDesc), len(file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDesc)))
	})
	return file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDescData
}

var file_google_ads_googleads_v19_resources_customer_asset_set_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v19_resources_customer_asset_set_proto_goTypes = []any{
	(*CustomerAssetSet)(nil),                             // 0: google.ads.googleads.v19.resources.CustomerAssetSet
	(enums.AssetSetLinkStatusEnum_AssetSetLinkStatus)(0), // 1: google.ads.googleads.v19.enums.AssetSetLinkStatusEnum.AssetSetLinkStatus
}
var file_google_ads_googleads_v19_resources_customer_asset_set_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v19.resources.CustomerAssetSet.status:type_name -> google.ads.googleads.v19.enums.AssetSetLinkStatusEnum.AssetSetLinkStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v19_resources_customer_asset_set_proto_init() }
func file_google_ads_googleads_v19_resources_customer_asset_set_proto_init() {
	if File_google_ads_googleads_v19_resources_customer_asset_set_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDesc), len(file_google_ads_googleads_v19_resources_customer_asset_set_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v19_resources_customer_asset_set_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v19_resources_customer_asset_set_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v19_resources_customer_asset_set_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v19_resources_customer_asset_set_proto = out.File
	file_google_ads_googleads_v19_resources_customer_asset_set_proto_goTypes = nil
	file_google_ads_googleads_v19_resources_customer_asset_set_proto_depIdxs = nil
}
