// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: google/ads/googleads/v20/resources/customer_sk_ad_network_conversion_value_schema.proto

package resources

import (
	enums "github.com/shenzhencenter/google-ads-pb/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A CustomerSkAdNetworkConversionValueSchema.
type CustomerSkAdNetworkConversionValueSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The resource name of the schema.
	// CustomerSkAdNetworkConversionValueSchema resource names have the form:
	// customers/{customer_id}/customerSkAdNetworkConversionValueSchemas/{account_link_id}
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Output only. The schema for the specified resource.
	Schema        *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerSkAdNetworkConversionValueSchema) Reset() {
	*x = CustomerSkAdNetworkConversionValueSchema{}
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSkAdNetworkConversionValueSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSkAdNetworkConversionValueSchema) ProtoMessage() {}

func (x *CustomerSkAdNetworkConversionValueSchema) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSkAdNetworkConversionValueSchema.ProtoReflect.Descriptor instead.
func (*CustomerSkAdNetworkConversionValueSchema) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerSkAdNetworkConversionValueSchema) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *CustomerSkAdNetworkConversionValueSchema) GetSchema() *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

// The CustomerLink specific SkAdNetworkConversionValueSchema.
type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Output only. Apple App Store app ID.
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Output only. A time window (measured in hours) post-install, after which
	// the App Attribution Partner or advertiser stops calling
	// [updateConversionValue]
	// (https://developer.apple.com/documentation/storekit/skadnetwork/3566697-updateconversionvalue).
	MeasurementWindowHours int32 `protobuf:"varint,2,opt,name=measurement_window_hours,json=measurementWindowHours,proto3" json:"measurement_window_hours,omitempty"`
	// Output only. Fine grained conversion value mappings.
	// For SkAdNetwork versions >= 4.0 that support multiple conversion
	// windows, fine grained conversion value mappings are only applicable to
	// the first postback.
	FineGrainedConversionValueMappings []*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings `protobuf:"bytes,3,rep,name=fine_grained_conversion_value_mappings,json=fineGrainedConversionValueMappings,proto3" json:"fine_grained_conversion_value_mappings,omitempty"`
	// Output only. Per-postback conversion value mappings for postbacks in
	// multiple conversion windows. Only applicable for SkAdNetwork versions
	// >= 4.0.
	PostbackMappings []*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping `protobuf:"bytes,4,rep,name=postback_mappings,json=postbackMappings,proto3" json:"postback_mappings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema) Reset() {
	*x = CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema{}
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema) ProtoMessage() {}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema.ProtoReflect.Descriptor instead.
func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema) GetMeasurementWindowHours() int32 {
	if x != nil {
		return x.MeasurementWindowHours
	}
	return 0
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema) GetFineGrainedConversionValueMappings() []*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings {
	if x != nil {
		return x.FineGrainedConversionValueMappings
	}
	return nil
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema) GetPostbackMappings() []*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping {
	if x != nil {
		return x.PostbackMappings
	}
	return nil
}

// Mappings for fine grained conversion value.
type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. Fine grained conversion value. Valid values are in the
	// inclusive range [0,63].
	FineGrainedConversionValue int32 `protobuf:"varint,1,opt,name=fine_grained_conversion_value,json=fineGrainedConversionValue,proto3" json:"fine_grained_conversion_value,omitempty"`
	// Output only. Conversion events the fine grained conversion value maps
	// to.
	ConversionValueMapping *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping `protobuf:"bytes,2,opt,name=conversion_value_mapping,json=conversionValueMapping,proto3" json:"conversion_value_mapping,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings) Reset() {
	*x = CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings{}
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings) ProtoMessage() {
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings.ProtoReflect.Descriptor instead.
func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings) GetFineGrainedConversionValue() int32 {
	if x != nil {
		return x.FineGrainedConversionValue
	}
	return 0
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings) GetConversionValueMapping() *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping {
	if x != nil {
		return x.ConversionValueMapping
	}
	return nil
}

// Mappings for each postback in multiple conversion windows.
type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. 0-based index that indicates the order of postback. Valid
	// values are in the inclusive range [0,2].
	PostbackSequenceIndex int32 `protobuf:"varint,1,opt,name=postback_sequence_index,json=postbackSequenceIndex,proto3" json:"postback_sequence_index,omitempty"`
	// Output only. Conversion value mappings for all coarse grained
	// conversion values.
	CoarseGrainedConversionValueMappings *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings `protobuf:"bytes,2,opt,name=coarse_grained_conversion_value_mappings,json=coarseGrainedConversionValueMappings,proto3" json:"coarse_grained_conversion_value_mappings,omitempty"`
	// Event or conversion value used for locking conversion window.
	//
	// Types that are valid to be assigned to LockWindowTrigger:
	//
	//	*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowCoarseConversionValue
	//	*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowFineConversionValue
	//	*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowEvent
	LockWindowTrigger isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowTrigger `protobuf_oneof:"lock_window_trigger"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping) Reset() {
	*x = CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping{}
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping) ProtoMessage() {
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping.ProtoReflect.Descriptor instead.
func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping) GetPostbackSequenceIndex() int32 {
	if x != nil {
		return x.PostbackSequenceIndex
	}
	return 0
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping) GetCoarseGrainedConversionValueMappings() *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings {
	if x != nil {
		return x.CoarseGrainedConversionValueMappings
	}
	return nil
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping) GetLockWindowTrigger() isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowTrigger {
	if x != nil {
		return x.LockWindowTrigger
	}
	return nil
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping) GetLockWindowCoarseConversionValue() enums.SkAdNetworkCoarseConversionValueEnum_SkAdNetworkCoarseConversionValue {
	if x != nil {
		if x, ok := x.LockWindowTrigger.(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowCoarseConversionValue); ok {
			return x.LockWindowCoarseConversionValue
		}
	}
	return enums.SkAdNetworkCoarseConversionValueEnum_SkAdNetworkCoarseConversionValue(0)
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping) GetLockWindowFineConversionValue() int32 {
	if x != nil {
		if x, ok := x.LockWindowTrigger.(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowFineConversionValue); ok {
			return x.LockWindowFineConversionValue
		}
	}
	return 0
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping) GetLockWindowEvent() string {
	if x != nil {
		if x, ok := x.LockWindowTrigger.(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowEvent); ok {
			return x.LockWindowEvent
		}
	}
	return ""
}

type isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowTrigger interface {
	isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowTrigger()
}

type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowCoarseConversionValue struct {
	// Output only. Coarse grained conversion value that triggers conversion
	// window lock.
	LockWindowCoarseConversionValue enums.SkAdNetworkCoarseConversionValueEnum_SkAdNetworkCoarseConversionValue `protobuf:"varint,3,opt,name=lock_window_coarse_conversion_value,json=lockWindowCoarseConversionValue,proto3,enum=google.ads.googleads.v20.enums.SkAdNetworkCoarseConversionValueEnum_SkAdNetworkCoarseConversionValue,oneof"`
}

type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowFineConversionValue struct {
	// Output only. Fine grained conversion value that triggers conversion
	// window lock.
	LockWindowFineConversionValue int32 `protobuf:"varint,4,opt,name=lock_window_fine_conversion_value,json=lockWindowFineConversionValue,proto3,oneof"`
}

type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowEvent struct {
	// Output only. Event name that triggers conversion window lock.
	LockWindowEvent string `protobuf:"bytes,5,opt,name=lock_window_event,json=lockWindowEvent,proto3,oneof"`
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowCoarseConversionValue) isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowTrigger() {
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowFineConversionValue) isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowTrigger() {
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowEvent) isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowTrigger() {
}

// Mappings for coarse grained conversion values.
type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. Mapping for "low" coarse conversion value.
	LowConversionValueMapping *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping `protobuf:"bytes,1,opt,name=low_conversion_value_mapping,json=lowConversionValueMapping,proto3" json:"low_conversion_value_mapping,omitempty"`
	// Output only. Mapping for "medium" coarse conversion value.
	MediumConversionValueMapping *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping `protobuf:"bytes,2,opt,name=medium_conversion_value_mapping,json=mediumConversionValueMapping,proto3" json:"medium_conversion_value_mapping,omitempty"`
	// Output only. Mapping for "high" coarse conversion value.
	HighConversionValueMapping *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping `protobuf:"bytes,3,opt,name=high_conversion_value_mapping,json=highConversionValueMapping,proto3" json:"high_conversion_value_mapping,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings) Reset() {
	*x = CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings{}
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings) ProtoMessage() {
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings.ProtoReflect.Descriptor instead.
func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings) GetLowConversionValueMapping() *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping {
	if x != nil {
		return x.LowConversionValueMapping
	}
	return nil
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings) GetMediumConversionValueMapping() *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping {
	if x != nil {
		return x.MediumConversionValueMapping
	}
	return nil
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings) GetHighConversionValueMapping() *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping {
	if x != nil {
		return x.HighConversionValueMapping
	}
	return nil
}

// Represents mapping from one conversion value to one or more conversion
// events.
type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The minimum of the time range in which a user was last
	// active during the measurement window.
	MinTimePostInstallHours int64 `protobuf:"varint,1,opt,name=min_time_post_install_hours,json=minTimePostInstallHours,proto3" json:"min_time_post_install_hours,omitempty"`
	// Output only. The maximum of the time range in which a user was last
	// active during the measurement window.
	MaxTimePostInstallHours int64 `protobuf:"varint,2,opt,name=max_time_post_install_hours,json=maxTimePostInstallHours,proto3" json:"max_time_post_install_hours,omitempty"`
	// Output only. The conversion value may be mapped to multiple events with
	// various attributes.
	MappedEvents  []*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event `protobuf:"bytes,3,rep,name=mapped_events,json=mappedEvents,proto3" json:"mapped_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping) Reset() {
	*x = CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping{}
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping) ProtoMessage() {
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping.ProtoReflect.Descriptor instead.
func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping) GetMinTimePostInstallHours() int64 {
	if x != nil {
		return x.MinTimePostInstallHours
	}
	return 0
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping) GetMaxTimePostInstallHours() int64 {
	if x != nil {
		return x.MaxTimePostInstallHours
	}
	return 0
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping) GetMappedEvents() []*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event {
	if x != nil {
		return x.MappedEvents
	}
	return nil
}

// Defines a Google conversion event that the conversion value is mapped to.
type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. Google event name represented by this conversion value.
	MappedEventName string `protobuf:"bytes,1,opt,name=mapped_event_name,json=mappedEventName,proto3" json:"mapped_event_name,omitempty"`
	// Output only. The reported currency for the event_revenue. ISO 4217
	// three-letter currency code, for example, "USD"
	CurrencyCode string `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	// Either a range or specific value for event revenue.
	//
	// Types that are valid to be assigned to RevenueRate:
	//
	//	*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRevenueRange
	//	*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRevenueValue
	RevenueRate isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRate `protobuf_oneof:"revenue_rate"`
	// Either a range or specific value for event counter.
	//
	// Types that are valid to be assigned to EventRate:
	//
	//	*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange_
	//	*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventCounter
	EventRate     isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRate `protobuf_oneof:"event_rate"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) Reset() {
	*x = CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event{}
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) ProtoMessage() {
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event.ProtoReflect.Descriptor instead.
func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescGZIP(), []int{0, 0, 4}
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) GetMappedEventName() string {
	if x != nil {
		return x.MappedEventName
	}
	return ""
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) GetRevenueRate() isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRate {
	if x != nil {
		return x.RevenueRate
	}
	return nil
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) GetEventRevenueRange() *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange {
	if x != nil {
		if x, ok := x.RevenueRate.(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRevenueRange); ok {
			return x.EventRevenueRange
		}
	}
	return nil
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) GetEventRevenueValue() float64 {
	if x != nil {
		if x, ok := x.RevenueRate.(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRevenueValue); ok {
			return x.EventRevenueValue
		}
	}
	return 0
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) GetEventRate() isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRate {
	if x != nil {
		return x.EventRate
	}
	return nil
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) GetEventOccurrenceRange() *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange {
	if x != nil {
		if x, ok := x.EventRate.(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange_); ok {
			return x.EventOccurrenceRange
		}
	}
	return nil
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event) GetEventCounter() int64 {
	if x != nil {
		if x, ok := x.EventRate.(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventCounter); ok {
			return x.EventCounter
		}
	}
	return 0
}

type isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRate interface {
	isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRate()
}

type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRevenueRange struct {
	// Output only. The event revenue range.
	EventRevenueRange *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange `protobuf:"bytes,3,opt,name=event_revenue_range,json=eventRevenueRange,proto3,oneof"`
}

type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRevenueValue struct {
	// Output only. The specific event revenue value.
	EventRevenueValue float64 `protobuf:"fixed64,4,opt,name=event_revenue_value,json=eventRevenueValue,proto3,oneof"`
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRevenueRange) isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRate() {
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRevenueValue) isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRate() {
}

type isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRate interface {
	isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRate()
}

type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange_ struct {
	// Output only. The event counter range.
	EventOccurrenceRange *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange `protobuf:"bytes,5,opt,name=event_occurrence_range,json=eventOccurrenceRange,proto3,oneof"`
}

type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventCounter struct {
	// Output only. For specific event counter values.
	EventCounter int64 `protobuf:"varint,6,opt,name=event_counter,json=eventCounter,proto3,oneof"`
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange_) isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRate() {
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventCounter) isCustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRate() {
}

// Defines a range for revenue values.
type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. For revenue ranges, the minimum value in `currency_code`
	// for which this conversion value would be updated. A value of 0 will
	// be treated as unset.
	MinEventRevenue float64 `protobuf:"fixed64,3,opt,name=min_event_revenue,json=minEventRevenue,proto3" json:"min_event_revenue,omitempty"`
	// Output only. For revenue ranges, the maximum value in `currency_code`
	// for which this conversion value would be updated. A value of 0 will
	// be treated as unset.
	MaxEventRevenue float64 `protobuf:"fixed64,4,opt,name=max_event_revenue,json=maxEventRevenue,proto3" json:"max_event_revenue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange) Reset() {
	*x = CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange{}
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange) ProtoMessage() {
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange.ProtoReflect.Descriptor instead.
func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescGZIP(), []int{0, 0, 4, 0}
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange) GetMinEventRevenue() float64 {
	if x != nil {
		return x.MinEventRevenue
	}
	return 0
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange) GetMaxEventRevenue() float64 {
	if x != nil {
		return x.MaxEventRevenue
	}
	return 0
}

// Defines a range for event counter values.
type CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. For event counter ranges, the minimum of the defined
	// range. A value of 0 will be treated as unset.
	MinEventCount int64 `protobuf:"varint,1,opt,name=min_event_count,json=minEventCount,proto3" json:"min_event_count,omitempty"`
	// Output only. For event counter ranges, the maximum of the defined
	// range. A value of 0 will be treated as unset.
	MaxEventCount int64 `protobuf:"varint,2,opt,name=max_event_count,json=maxEventCount,proto3" json:"max_event_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange) Reset() {
	*x = CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange{}
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange) ProtoMessage() {
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange.ProtoReflect.Descriptor instead.
func (*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescGZIP(), []int{0, 0, 4, 1}
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange) GetMinEventCount() int64 {
	if x != nil {
		return x.MinEventCount
	}
	return 0
}

func (x *CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange) GetMaxEventCount() int64 {
	if x != nil {
		return x.MaxEventCount
	}
	return 0
}

var File_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDesc = "" +
	"\n" +
	"Wgoogle/ads/googleads/v20/resources/customer_sk_ad_network_conversion_value_schema.proto\x12\"google.ads.googleads.v20.resources\x1aJgoogle/ads/googleads/v20/enums/sk_ad_network_coarse_conversion_value.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xe4\x1d\n" +
	"(CustomerSkAdNetworkConversionValueSchema\x12n\n" +
	"\rresource_name\x18\x01 \x01(\tBI\xe0A\x03\xfaAC\n" +
	"Agoogleads.googleapis.com/CustomerSkAdNetworkConversionValueSchemaR\fresourceName\x12\x8a\x01\n" +
	"\x06schema\x18\x02 \x01(\v2m.google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchemaB\x03\xe0A\x03R\x06schema\x1a\x9b\x1a\n" +
	" SkAdNetworkConversionValueSchema\x12\x1d\n" +
	"\x06app_id\x18\x01 \x01(\tB\x06\xe0A\x02\xe0A\x03R\x05appId\x12=\n" +
	"\x18measurement_window_hours\x18\x02 \x01(\x05B\x03\xe0A\x03R\x16measurementWindowHours\x12\xea\x01\n" +
	"&fine_grained_conversion_value_mappings\x18\x03 \x03(\v2\x90\x01.google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.FineGrainedConversionValueMappingsB\x03\xe0A\x03R\"fineGrainedConversionValueMappings\x12\xaf\x01\n" +
	"\x11postback_mappings\x18\x04 \x03(\v2}.google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.PostbackMappingB\x03\xe0A\x03R\x10postbackMappings\x1a\xb3\x02\n" +
	"\"FineGrainedConversionValueMappings\x12F\n" +
	"\x1dfine_grained_conversion_value\x18\x01 \x01(\x05B\x03\xe0A\x03R\x1afineGrainedConversionValue\x12\xc4\x01\n" +
	"\x18conversion_value_mapping\x18\x02 \x01(\v2\x84\x01.google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.ConversionValueMappingB\x03\xe0A\x03R\x16conversionValueMapping\x1a\x99\x05\n" +
	"\x0fPostbackMapping\x12;\n" +
	"\x17postback_sequence_index\x18\x01 \x01(\x05B\x03\xe0A\x03R\x15postbackSequenceIndex\x12\xf0\x01\n" +
	"(coarse_grained_conversion_value_mappings\x18\x02 \x01(\v2\x92\x01.google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.CoarseGrainedConversionValueMappingsB\x03\xe0A\x03R$coarseGrainedConversionValueMappings\x12\xba\x01\n" +
	"#lock_window_coarse_conversion_value\x18\x03 \x01(\x0e2e.google.ads.googleads.v20.enums.SkAdNetworkCoarseConversionValueEnum.SkAdNetworkCoarseConversionValueB\x03\xe0A\x03H\x00R\x1flockWindowCoarseConversionValue\x12O\n" +
	"!lock_window_fine_conversion_value\x18\x04 \x01(\x05B\x03\xe0A\x03H\x00R\x1dlockWindowFineConversionValue\x121\n" +
	"\x11lock_window_event\x18\x05 \x01(\tB\x03\xe0A\x03H\x00R\x0flockWindowEventB\x15\n" +
	"\x13lock_window_trigger\x1a\x98\x05\n" +
	"$CoarseGrainedConversionValueMappings\x12\xcb\x01\n" +
	"\x1clow_conversion_value_mapping\x18\x01 \x01(\v2\x84\x01.google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.ConversionValueMappingB\x03\xe0A\x03R\x19lowConversionValueMapping\x12\xd1\x01\n" +
	"\x1fmedium_conversion_value_mapping\x18\x02 \x01(\v2\x84\x01.google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.ConversionValueMappingB\x03\xe0A\x03R\x1cmediumConversionValueMapping\x12\xcd\x01\n" +
	"\x1dhigh_conversion_value_mapping\x18\x03 \x01(\v2\x84\x01.google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.ConversionValueMappingB\x03\xe0A\x03R\x1ahighConversionValueMapping\x1a\xbe\x02\n" +
	"\x16ConversionValueMapping\x12A\n" +
	"\x1bmin_time_post_install_hours\x18\x01 \x01(\x03B\x03\xe0A\x03R\x17minTimePostInstallHours\x12A\n" +
	"\x1bmax_time_post_install_hours\x18\x02 \x01(\x03B\x03\xe0A\x03R\x17maxTimePostInstallHours\x12\x9d\x01\n" +
	"\rmapped_events\x18\x03 \x03(\v2s.google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.EventB\x03\xe0A\x03R\fmappedEvents\x1a\xcb\x06\n" +
	"\x05Event\x12/\n" +
	"\x11mapped_event_name\x18\x01 \x01(\tB\x03\xe0A\x03R\x0fmappedEventName\x12(\n" +
	"\rcurrency_code\x18\x02 \x01(\tB\x03\xe0A\x03R\fcurrencyCode\x12\xb8\x01\n" +
	"\x13event_revenue_range\x18\x03 \x01(\v2\x80\x01.google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.Event.RevenueRangeB\x03\xe0A\x03H\x00R\x11eventRevenueRange\x125\n" +
	"\x13event_revenue_value\x18\x04 \x01(\x01B\x03\xe0A\x03H\x00R\x11eventRevenueValue\x12\xc6\x01\n" +
	"\x16event_occurrence_range\x18\x05 \x01(\v2\x88\x01.google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.Event.EventOccurrenceRangeB\x03\xe0A\x03H\x01R\x14eventOccurrenceRange\x12*\n" +
	"\revent_counter\x18\x06 \x01(\x03B\x03\xe0A\x03H\x01R\feventCounter\x1ap\n" +
	"\fRevenueRange\x12/\n" +
	"\x11min_event_revenue\x18\x03 \x01(\x01B\x03\xe0A\x03R\x0fminEventRevenue\x12/\n" +
	"\x11max_event_revenue\x18\x04 \x01(\x01B\x03\xe0A\x03R\x0fmaxEventRevenue\x1ap\n" +
	"\x14EventOccurrenceRange\x12+\n" +
	"\x0fmin_event_count\x18\x01 \x01(\x03B\x03\xe0A\x03R\rminEventCount\x12+\n" +
	"\x0fmax_event_count\x18\x02 \x01(\x03B\x03\xe0A\x03R\rmaxEventCountB\x0e\n" +
	"\frevenue_rateB\f\n" +
	"\n" +
	"event_rate:\x9c\x01\xeaA\x98\x01\n" +
	"Agoogleads.googleapis.com/CustomerSkAdNetworkConversionValueSchema\x12Scustomers/{customer_id}/customerSkAdNetworkConversionValueSchemas/{account_link_id}B\x9f\x02\n" +
	"&com.google.ads.googleads.v20.resourcesB-CustomerSkAdNetworkConversionValueSchemaProtoP\x01ZKgithub.com/shenzhencenter/google-ads-pb/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V20.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V20\\Resources\xea\x02&Google::Ads::GoogleAds::V20::Resourcesb\x06proto3"

var (
	file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescData []byte
)

func file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDesc), len(file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDesc)))
	})
	return file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDescData
}

var file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_goTypes = []any{
	(*CustomerSkAdNetworkConversionValueSchema)(nil),                                                                       // 0: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema
	(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema)(nil),                                      // 1: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema
	(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_FineGrainedConversionValueMappings)(nil),   // 2: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.FineGrainedConversionValueMappings
	(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping)(nil),                      // 3: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.PostbackMapping
	(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_CoarseGrainedConversionValueMappings)(nil), // 4: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.CoarseGrainedConversionValueMappings
	(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_ConversionValueMapping)(nil),               // 5: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.ConversionValueMapping
	(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event)(nil),                                // 6: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.Event
	(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_RevenueRange)(nil),                   // 7: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.Event.RevenueRange
	(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange)(nil),           // 8: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.Event.EventOccurrenceRange
	(enums.SkAdNetworkCoarseConversionValueEnum_SkAdNetworkCoarseConversionValue)(0),                                       // 9: google.ads.googleads.v20.enums.SkAdNetworkCoarseConversionValueEnum.SkAdNetworkCoarseConversionValue
}
var file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_depIdxs = []int32{
	1,  // 0: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.schema:type_name -> google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema
	2,  // 1: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.fine_grained_conversion_value_mappings:type_name -> google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.FineGrainedConversionValueMappings
	3,  // 2: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.postback_mappings:type_name -> google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.PostbackMapping
	5,  // 3: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.FineGrainedConversionValueMappings.conversion_value_mapping:type_name -> google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.ConversionValueMapping
	4,  // 4: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.PostbackMapping.coarse_grained_conversion_value_mappings:type_name -> google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.CoarseGrainedConversionValueMappings
	9,  // 5: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.PostbackMapping.lock_window_coarse_conversion_value:type_name -> google.ads.googleads.v20.enums.SkAdNetworkCoarseConversionValueEnum.SkAdNetworkCoarseConversionValue
	5,  // 6: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.CoarseGrainedConversionValueMappings.low_conversion_value_mapping:type_name -> google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.ConversionValueMapping
	5,  // 7: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.CoarseGrainedConversionValueMappings.medium_conversion_value_mapping:type_name -> google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.ConversionValueMapping
	5,  // 8: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.CoarseGrainedConversionValueMappings.high_conversion_value_mapping:type_name -> google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.ConversionValueMapping
	6,  // 9: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.ConversionValueMapping.mapped_events:type_name -> google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.Event
	7,  // 10: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.Event.event_revenue_range:type_name -> google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.Event.RevenueRange
	8,  // 11: google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.Event.event_occurrence_range:type_name -> google.ads.googleads.v20.resources.CustomerSkAdNetworkConversionValueSchema.SkAdNetworkConversionValueSchema.Event.EventOccurrenceRange
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() {
	file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_init()
}
func file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_init() {
	if File_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto != nil {
		return
	}
	file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[3].OneofWrappers = []any{
		(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowCoarseConversionValue)(nil),
		(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowFineConversionValue)(nil),
		(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_PostbackMapping_LockWindowEvent)(nil),
	}
	file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes[6].OneofWrappers = []any{
		(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRevenueRange)(nil),
		(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventRevenueValue)(nil),
		(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventOccurrenceRange_)(nil),
		(*CustomerSkAdNetworkConversionValueSchema_SkAdNetworkConversionValueSchema_Event_EventCounter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDesc), len(file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto = out.File
	file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_goTypes = nil
	file_google_ads_googleads_v20_resources_customer_sk_ad_network_conversion_value_schema_proto_depIdxs = nil
}
