// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: google/ads/googleads/v19/resources/payments_account.proto

package resources

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A payments account, which can be used to set up billing for an Ads customer.
type PaymentsAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The resource name of the payments account.
	// PaymentsAccount resource names have the form:
	//
	// `customers/{customer_id}/paymentsAccounts/{payments_account_id}`
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Output only. A 16 digit ID used to identify a payments account.
	PaymentsAccountId *string `protobuf:"bytes,8,opt,name=payments_account_id,json=paymentsAccountId,proto3,oneof" json:"payments_account_id,omitempty"`
	// Output only. The name of the payments account.
	Name *string `protobuf:"bytes,9,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Output only. The currency code of the payments account.
	// A subset of the currency codes derived from the ISO 4217 standard is
	// supported.
	CurrencyCode *string `protobuf:"bytes,10,opt,name=currency_code,json=currencyCode,proto3,oneof" json:"currency_code,omitempty"`
	// Output only. A 12 digit ID used to identify the payments profile associated
	// with the payments account.
	PaymentsProfileId *string `protobuf:"bytes,11,opt,name=payments_profile_id,json=paymentsProfileId,proto3,oneof" json:"payments_profile_id,omitempty"`
	// Output only. A secondary payments profile ID present in uncommon
	// situations, for example, when a sequential liability agreement has been
	// arranged.
	SecondaryPaymentsProfileId *string `protobuf:"bytes,12,opt,name=secondary_payments_profile_id,json=secondaryPaymentsProfileId,proto3,oneof" json:"secondary_payments_profile_id,omitempty"`
	// Output only. Paying manager of this payment account.
	PayingManagerCustomer *string `protobuf:"bytes,13,opt,name=paying_manager_customer,json=payingManagerCustomer,proto3,oneof" json:"paying_manager_customer,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PaymentsAccount) Reset() {
	*x = PaymentsAccount{}
	mi := &file_google_ads_googleads_v19_resources_payments_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentsAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentsAccount) ProtoMessage() {}

func (x *PaymentsAccount) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v19_resources_payments_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentsAccount.ProtoReflect.Descriptor instead.
func (*PaymentsAccount) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v19_resources_payments_account_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentsAccount) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *PaymentsAccount) GetPaymentsAccountId() string {
	if x != nil && x.PaymentsAccountId != nil {
		return *x.PaymentsAccountId
	}
	return ""
}

func (x *PaymentsAccount) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PaymentsAccount) GetCurrencyCode() string {
	if x != nil && x.CurrencyCode != nil {
		return *x.CurrencyCode
	}
	return ""
}

func (x *PaymentsAccount) GetPaymentsProfileId() string {
	if x != nil && x.PaymentsProfileId != nil {
		return *x.PaymentsProfileId
	}
	return ""
}

func (x *PaymentsAccount) GetSecondaryPaymentsProfileId() string {
	if x != nil && x.SecondaryPaymentsProfileId != nil {
		return *x.SecondaryPaymentsProfileId
	}
	return ""
}

func (x *PaymentsAccount) GetPayingManagerCustomer() string {
	if x != nil && x.PayingManagerCustomer != nil {
		return *x.PayingManagerCustomer
	}
	return ""
}

var File_google_ads_googleads_v19_resources_payments_account_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v19_resources_payments_account_proto_rawDesc = "" +
	"\n" +
	"9google/ads/googleads/v19/resources/payments_account.proto\x12\"google.ads.googleads.v19.resources\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xd6\x05\n" +
	"\x0fPaymentsAccount\x12U\n" +
	"\rresource_name\x18\x01 \x01(\tB0\xe0A\x03\xfaA*\n" +
	"(googleads.googleapis.com/PaymentsAccountR\fresourceName\x128\n" +
	"\x13payments_account_id\x18\b \x01(\tB\x03\xe0A\x03H\x00R\x11paymentsAccountId\x88\x01\x01\x12\x1c\n" +
	"\x04name\x18\t \x01(\tB\x03\xe0A\x03H\x01R\x04name\x88\x01\x01\x12-\n" +
	"\rcurrency_code\x18\n" +
	" \x01(\tB\x03\xe0A\x03H\x02R\fcurrencyCode\x88\x01\x01\x128\n" +
	"\x13payments_profile_id\x18\v \x01(\tB\x03\xe0A\x03H\x03R\x11paymentsProfileId\x88\x01\x01\x12K\n" +
	"\x1dsecondary_payments_profile_id\x18\f \x01(\tB\x03\xe0A\x03H\x04R\x1asecondaryPaymentsProfileId\x88\x01\x01\x12f\n" +
	"\x17paying_manager_customer\x18\r \x01(\tB)\xe0A\x03\xfaA#\n" +
	"!googleads.googleapis.com/CustomerH\x05R\x15payingManagerCustomer\x88\x01\x01:m\xeaAj\n" +
	"(googleads.googleapis.com/PaymentsAccount\x12>customers/{customer_id}/paymentsAccounts/{payments_account_id}B\x16\n" +
	"\x14_payments_account_idB\a\n" +
	"\x05_nameB\x10\n" +
	"\x0e_currency_codeB\x16\n" +
	"\x14_payments_profile_idB \n" +
	"\x1e_secondary_payments_profile_idB\x1a\n" +
	"\x18_paying_manager_customerB\x86\x02\n" +
	"&com.google.ads.googleads.v19.resourcesB\x14PaymentsAccountProtoP\x01ZKgithub.com/shenzhencenter/google-ads-pb/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V19.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V19\\Resources\xea\x02&Google::Ads::GoogleAds::V19::Resourcesb\x06proto3"

var (
	file_google_ads_googleads_v19_resources_payments_account_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v19_resources_payments_account_proto_rawDescData []byte
)

func file_google_ads_googleads_v19_resources_payments_account_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v19_resources_payments_account_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v19_resources_payments_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_resources_payments_account_proto_rawDesc), len(file_google_ads_googleads_v19_resources_payments_account_proto_rawDesc)))
	})
	return file_google_ads_googleads_v19_resources_payments_account_proto_rawDescData
}

var file_google_ads_googleads_v19_resources_payments_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v19_resources_payments_account_proto_goTypes = []any{
	(*PaymentsAccount)(nil), // 0: google.ads.googleads.v19.resources.PaymentsAccount
}
var file_google_ads_googleads_v19_resources_payments_account_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v19_resources_payments_account_proto_init() }
func file_google_ads_googleads_v19_resources_payments_account_proto_init() {
	if File_google_ads_googleads_v19_resources_payments_account_proto != nil {
		return
	}
	file_google_ads_googleads_v19_resources_payments_account_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_resources_payments_account_proto_rawDesc), len(file_google_ads_googleads_v19_resources_payments_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v19_resources_payments_account_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v19_resources_payments_account_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v19_resources_payments_account_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v19_resources_payments_account_proto = out.File
	file_google_ads_googleads_v19_resources_payments_account_proto_goTypes = nil
	file_google_ads_googleads_v19_resources_payments_account_proto_depIdxs = nil
}
