// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: google/ads/googleads/v20/services/ad_group_criterion_service.proto

package services

import (
	common "github.com/shenzhencenter/google-ads-pb/common"
	enums "github.com/shenzhencenter/google-ads-pb/enums"
	resources "github.com/shenzhencenter/google-ads-pb/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for
// [AdGroupCriterionService.MutateAdGroupCriteria][google.ads.googleads.v20.services.AdGroupCriterionService.MutateAdGroupCriteria].
type MutateAdGroupCriteriaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. ID of the customer whose criteria are being modified.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Required. The list of operations to perform on individual criteria.
	Operations []*AdGroupCriterionOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	// If true, successful operations will be carried out and invalid
	// operations will return errors. If false, all operations will be carried
	// out in one transaction if and only if they are all valid.
	// Default is false.
	PartialFailure bool `protobuf:"varint,3,opt,name=partial_failure,json=partialFailure,proto3" json:"partial_failure,omitempty"`
	// If true, the request is validated but not executed. Only errors are
	// returned, not results.
	ValidateOnly bool `protobuf:"varint,4,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	// The response content type setting. Determines whether the mutable resource
	// or just the resource name should be returned post mutation.
	ResponseContentType enums.ResponseContentTypeEnum_ResponseContentType `protobuf:"varint,5,opt,name=response_content_type,json=responseContentType,proto3,enum=google.ads.googleads.v20.enums.ResponseContentTypeEnum_ResponseContentType" json:"response_content_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MutateAdGroupCriteriaRequest) Reset() {
	*x = MutateAdGroupCriteriaRequest{}
	mi := &file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateAdGroupCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateAdGroupCriteriaRequest) ProtoMessage() {}

func (x *MutateAdGroupCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateAdGroupCriteriaRequest.ProtoReflect.Descriptor instead.
func (*MutateAdGroupCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDescGZIP(), []int{0}
}

func (x *MutateAdGroupCriteriaRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *MutateAdGroupCriteriaRequest) GetOperations() []*AdGroupCriterionOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *MutateAdGroupCriteriaRequest) GetPartialFailure() bool {
	if x != nil {
		return x.PartialFailure
	}
	return false
}

func (x *MutateAdGroupCriteriaRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

func (x *MutateAdGroupCriteriaRequest) GetResponseContentType() enums.ResponseContentTypeEnum_ResponseContentType {
	if x != nil {
		return x.ResponseContentType
	}
	return enums.ResponseContentTypeEnum_ResponseContentType(0)
}

// A single operation (create, remove, update) on an ad group criterion.
type AdGroupCriterionOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FieldMask that determines which resource fields are modified in an update.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// The list of policy violation keys that should not cause a
	// PolicyViolationError to be reported. Not all policy violations are
	// exemptable, refer to the is_exemptible field in the returned
	// PolicyViolationError.
	//
	// Resources violating these polices will be saved, but will not be eligible
	// to serve. They may begin serving at a later time due to a change in
	// policies, re-review of the resource, or a change in advertiser
	// certificates.
	ExemptPolicyViolationKeys []*common.PolicyViolationKey `protobuf:"bytes,5,rep,name=exempt_policy_violation_keys,json=exemptPolicyViolationKeys,proto3" json:"exempt_policy_violation_keys,omitempty"`
	// The mutate operation.
	//
	// Types that are valid to be assigned to Operation:
	//
	//	*AdGroupCriterionOperation_Create
	//	*AdGroupCriterionOperation_Update
	//	*AdGroupCriterionOperation_Remove
	Operation     isAdGroupCriterionOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdGroupCriterionOperation) Reset() {
	*x = AdGroupCriterionOperation{}
	mi := &file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdGroupCriterionOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdGroupCriterionOperation) ProtoMessage() {}

func (x *AdGroupCriterionOperation) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdGroupCriterionOperation.ProtoReflect.Descriptor instead.
func (*AdGroupCriterionOperation) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDescGZIP(), []int{1}
}

func (x *AdGroupCriterionOperation) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *AdGroupCriterionOperation) GetExemptPolicyViolationKeys() []*common.PolicyViolationKey {
	if x != nil {
		return x.ExemptPolicyViolationKeys
	}
	return nil
}

func (x *AdGroupCriterionOperation) GetOperation() isAdGroupCriterionOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *AdGroupCriterionOperation) GetCreate() *resources.AdGroupCriterion {
	if x != nil {
		if x, ok := x.Operation.(*AdGroupCriterionOperation_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *AdGroupCriterionOperation) GetUpdate() *resources.AdGroupCriterion {
	if x != nil {
		if x, ok := x.Operation.(*AdGroupCriterionOperation_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *AdGroupCriterionOperation) GetRemove() string {
	if x != nil {
		if x, ok := x.Operation.(*AdGroupCriterionOperation_Remove); ok {
			return x.Remove
		}
	}
	return ""
}

type isAdGroupCriterionOperation_Operation interface {
	isAdGroupCriterionOperation_Operation()
}

type AdGroupCriterionOperation_Create struct {
	// Create operation: No resource name is expected for the new criterion.
	Create *resources.AdGroupCriterion `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type AdGroupCriterionOperation_Update struct {
	// Update operation: The criterion is expected to have a valid resource
	// name.
	Update *resources.AdGroupCriterion `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type AdGroupCriterionOperation_Remove struct {
	// Remove operation: A resource name for the removed criterion is expected,
	// in this format:
	//
	// `customers/{customer_id}/adGroupCriteria/{ad_group_id}~{criterion_id}`
	Remove string `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

func (*AdGroupCriterionOperation_Create) isAdGroupCriterionOperation_Operation() {}

func (*AdGroupCriterionOperation_Update) isAdGroupCriterionOperation_Operation() {}

func (*AdGroupCriterionOperation_Remove) isAdGroupCriterionOperation_Operation() {}

// Response message for an ad group criterion mutate.
type MutateAdGroupCriteriaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Errors that pertain to operation failures in the partial failure mode.
	// Returned only when partial_failure = true and all errors occur inside the
	// operations. If any errors occur outside the operations (for example, auth
	// errors), we return an RPC level error.
	PartialFailureError *status.Status `protobuf:"bytes,3,opt,name=partial_failure_error,json=partialFailureError,proto3" json:"partial_failure_error,omitempty"`
	// All results for the mutate.
	Results       []*MutateAdGroupCriterionResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateAdGroupCriteriaResponse) Reset() {
	*x = MutateAdGroupCriteriaResponse{}
	mi := &file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateAdGroupCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateAdGroupCriteriaResponse) ProtoMessage() {}

func (x *MutateAdGroupCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateAdGroupCriteriaResponse.ProtoReflect.Descriptor instead.
func (*MutateAdGroupCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDescGZIP(), []int{2}
}

func (x *MutateAdGroupCriteriaResponse) GetPartialFailureError() *status.Status {
	if x != nil {
		return x.PartialFailureError
	}
	return nil
}

func (x *MutateAdGroupCriteriaResponse) GetResults() []*MutateAdGroupCriterionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// The result for the criterion mutate.
type MutateAdGroupCriterionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returned for successful operations.
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// The mutated ad group criterion with only mutable fields after mutate. The
	// field will only be returned when response_content_type is set to
	// "MUTABLE_RESOURCE".
	AdGroupCriterion *resources.AdGroupCriterion `protobuf:"bytes,2,opt,name=ad_group_criterion,json=adGroupCriterion,proto3" json:"ad_group_criterion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MutateAdGroupCriterionResult) Reset() {
	*x = MutateAdGroupCriterionResult{}
	mi := &file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateAdGroupCriterionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateAdGroupCriterionResult) ProtoMessage() {}

func (x *MutateAdGroupCriterionResult) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateAdGroupCriterionResult.ProtoReflect.Descriptor instead.
func (*MutateAdGroupCriterionResult) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDescGZIP(), []int{3}
}

func (x *MutateAdGroupCriterionResult) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *MutateAdGroupCriterionResult) GetAdGroupCriterion() *resources.AdGroupCriterion {
	if x != nil {
		return x.AdGroupCriterion
	}
	return nil
}

var File_google_ads_googleads_v20_services_ad_group_criterion_service_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDesc = "" +
	"\n" +
	"Bgoogle/ads/googleads/v20/services/ad_group_criterion_service.proto\x12!google.ads.googleads.v20.services\x1a,google/ads/googleads/v20/common/policy.proto\x1a:google/ads/googleads/v20/enums/response_content_type.proto\x1a;google/ads/googleads/v20/resources/ad_group_criterion.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x17google/rpc/status.proto\"\xf6\x02\n" +
	"\x1cMutateAdGroupCriteriaRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12a\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2<.google.ads.googleads.v20.services.AdGroupCriterionOperationB\x03\xe0A\x02R\n" +
	"operations\x12'\n" +
	"\x0fpartial_failure\x18\x03 \x01(\bR\x0epartialFailure\x12#\n" +
	"\rvalidate_only\x18\x04 \x01(\bR\fvalidateOnly\x12\x7f\n" +
	"\x15response_content_type\x18\x05 \x01(\x0e2K.google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentTypeR\x13responseContentType\"\xc5\x03\n" +
	"\x19AdGroupCriterionOperation\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12t\n" +
	"\x1cexempt_policy_violation_keys\x18\x05 \x03(\v23.google.ads.googleads.v20.common.PolicyViolationKeyR\x19exemptPolicyViolationKeys\x12N\n" +
	"\x06create\x18\x01 \x01(\v24.google.ads.googleads.v20.resources.AdGroupCriterionH\x00R\x06create\x12N\n" +
	"\x06update\x18\x02 \x01(\v24.google.ads.googleads.v20.resources.AdGroupCriterionH\x00R\x06update\x12H\n" +
	"\x06remove\x18\x03 \x01(\tB.\xfaA+\n" +
	")googleads.googleapis.com/AdGroupCriterionH\x00R\x06removeB\v\n" +
	"\toperation\"\xc2\x01\n" +
	"\x1dMutateAdGroupCriteriaResponse\x12F\n" +
	"\x15partial_failure_error\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x13partialFailureError\x12Y\n" +
	"\aresults\x18\x02 \x03(\v2?.google.ads.googleads.v20.services.MutateAdGroupCriterionResultR\aresults\"\xd7\x01\n" +
	"\x1cMutateAdGroupCriterionResult\x12S\n" +
	"\rresource_name\x18\x01 \x01(\tB.\xfaA+\n" +
	")googleads.googleapis.com/AdGroupCriterionR\fresourceName\x12b\n" +
	"\x12ad_group_criterion\x18\x02 \x01(\v24.google.ads.googleads.v20.resources.AdGroupCriterionR\x10adGroupCriterion2\xd8\x02\n" +
	"\x17AdGroupCriterionService\x12\xf5\x01\n" +
	"\x15MutateAdGroupCriteria\x12?.google.ads.googleads.v20.services.MutateAdGroupCriteriaRequest\x1a@.google.ads.googleads.v20.services.MutateAdGroupCriteriaResponse\"Y\xdaA\x16customer_id,operations\x82\xd3\xe4\x93\x02::\x01*\"5/v20/customers/{customer_id=*}/adGroupCriteria:mutate\x1aE\xcaA\x18googleads.googleapis.com\xd2A'https://www.googleapis.com/auth/adwordsB\x88\x02\n" +
	"%com.google.ads.googleads.v20.servicesB\x1cAdGroupCriterionServiceProtoP\x01ZIgithub.com/shenzhencenter/google-ads-pb/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V20.Services\xca\x02!Google\\Ads\\GoogleAds\\V20\\Services\xea\x02%Google::Ads::GoogleAds::V20::Servicesb\x06proto3"

var (
	file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDescData []byte
)

func file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDesc), len(file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDesc)))
	})
	return file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDescData
}

var file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_goTypes = []any{
	(*MutateAdGroupCriteriaRequest)(nil),                   // 0: google.ads.googleads.v20.services.MutateAdGroupCriteriaRequest
	(*AdGroupCriterionOperation)(nil),                      // 1: google.ads.googleads.v20.services.AdGroupCriterionOperation
	(*MutateAdGroupCriteriaResponse)(nil),                  // 2: google.ads.googleads.v20.services.MutateAdGroupCriteriaResponse
	(*MutateAdGroupCriterionResult)(nil),                   // 3: google.ads.googleads.v20.services.MutateAdGroupCriterionResult
	(enums.ResponseContentTypeEnum_ResponseContentType)(0), // 4: google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentType
	(*fieldmaskpb.FieldMask)(nil),                          // 5: google.protobuf.FieldMask
	(*common.PolicyViolationKey)(nil),                      // 6: google.ads.googleads.v20.common.PolicyViolationKey
	(*resources.AdGroupCriterion)(nil),                     // 7: google.ads.googleads.v20.resources.AdGroupCriterion
	(*status.Status)(nil),                                  // 8: google.rpc.Status
}
var file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_depIdxs = []int32{
	1,  // 0: google.ads.googleads.v20.services.MutateAdGroupCriteriaRequest.operations:type_name -> google.ads.googleads.v20.services.AdGroupCriterionOperation
	4,  // 1: google.ads.googleads.v20.services.MutateAdGroupCriteriaRequest.response_content_type:type_name -> google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentType
	5,  // 2: google.ads.googleads.v20.services.AdGroupCriterionOperation.update_mask:type_name -> google.protobuf.FieldMask
	6,  // 3: google.ads.googleads.v20.services.AdGroupCriterionOperation.exempt_policy_violation_keys:type_name -> google.ads.googleads.v20.common.PolicyViolationKey
	7,  // 4: google.ads.googleads.v20.services.AdGroupCriterionOperation.create:type_name -> google.ads.googleads.v20.resources.AdGroupCriterion
	7,  // 5: google.ads.googleads.v20.services.AdGroupCriterionOperation.update:type_name -> google.ads.googleads.v20.resources.AdGroupCriterion
	8,  // 6: google.ads.googleads.v20.services.MutateAdGroupCriteriaResponse.partial_failure_error:type_name -> google.rpc.Status
	3,  // 7: google.ads.googleads.v20.services.MutateAdGroupCriteriaResponse.results:type_name -> google.ads.googleads.v20.services.MutateAdGroupCriterionResult
	7,  // 8: google.ads.googleads.v20.services.MutateAdGroupCriterionResult.ad_group_criterion:type_name -> google.ads.googleads.v20.resources.AdGroupCriterion
	0,  // 9: google.ads.googleads.v20.services.AdGroupCriterionService.MutateAdGroupCriteria:input_type -> google.ads.googleads.v20.services.MutateAdGroupCriteriaRequest
	2,  // 10: google.ads.googleads.v20.services.AdGroupCriterionService.MutateAdGroupCriteria:output_type -> google.ads.googleads.v20.services.MutateAdGroupCriteriaResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_init() }
func file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_init() {
	if File_google_ads_googleads_v20_services_ad_group_criterion_service_proto != nil {
		return
	}
	file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_msgTypes[1].OneofWrappers = []any{
		(*AdGroupCriterionOperation_Create)(nil),
		(*AdGroupCriterionOperation_Update)(nil),
		(*AdGroupCriterionOperation_Remove)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDesc), len(file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v20_services_ad_group_criterion_service_proto = out.File
	file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_goTypes = nil
	file_google_ads_googleads_v20_services_ad_group_criterion_service_proto_depIdxs = nil
}
