// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: google/ads/googleads/v20/services/customer_client_link_service.proto

package services

import (
	resources "github.com/shenzhencenter/google-ads-pb/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for
// [CustomerClientLinkService.MutateCustomerClientLink][google.ads.googleads.v20.services.CustomerClientLinkService.MutateCustomerClientLink].
type MutateCustomerClientLinkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the customer whose customer link are being modified.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Required. The operation to perform on the individual CustomerClientLink.
	Operation *CustomerClientLinkOperation `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// If true, the request is validated but not executed. Only errors are
	// returned, not results.
	ValidateOnly  bool `protobuf:"varint,3,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateCustomerClientLinkRequest) Reset() {
	*x = MutateCustomerClientLinkRequest{}
	mi := &file_google_ads_googleads_v20_services_customer_client_link_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateCustomerClientLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateCustomerClientLinkRequest) ProtoMessage() {}

func (x *MutateCustomerClientLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_customer_client_link_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateCustomerClientLinkRequest.ProtoReflect.Descriptor instead.
func (*MutateCustomerClientLinkRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDescGZIP(), []int{0}
}

func (x *MutateCustomerClientLinkRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *MutateCustomerClientLinkRequest) GetOperation() *CustomerClientLinkOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *MutateCustomerClientLinkRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

// A single operation (create, update) on a CustomerClientLink.
type CustomerClientLinkOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FieldMask that determines which resource fields are modified in an update.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// The mutate operation.
	//
	// Types that are valid to be assigned to Operation:
	//
	//	*CustomerClientLinkOperation_Create
	//	*CustomerClientLinkOperation_Update
	Operation     isCustomerClientLinkOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerClientLinkOperation) Reset() {
	*x = CustomerClientLinkOperation{}
	mi := &file_google_ads_googleads_v20_services_customer_client_link_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerClientLinkOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerClientLinkOperation) ProtoMessage() {}

func (x *CustomerClientLinkOperation) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_customer_client_link_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerClientLinkOperation.ProtoReflect.Descriptor instead.
func (*CustomerClientLinkOperation) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerClientLinkOperation) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *CustomerClientLinkOperation) GetOperation() isCustomerClientLinkOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *CustomerClientLinkOperation) GetCreate() *resources.CustomerClientLink {
	if x != nil {
		if x, ok := x.Operation.(*CustomerClientLinkOperation_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *CustomerClientLinkOperation) GetUpdate() *resources.CustomerClientLink {
	if x != nil {
		if x, ok := x.Operation.(*CustomerClientLinkOperation_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isCustomerClientLinkOperation_Operation interface {
	isCustomerClientLinkOperation_Operation()
}

type CustomerClientLinkOperation_Create struct {
	// Create operation: No resource name is expected for the new link.
	Create *resources.CustomerClientLink `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type CustomerClientLinkOperation_Update struct {
	// Update operation: The link is expected to have a valid resource name.
	Update *resources.CustomerClientLink `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

func (*CustomerClientLinkOperation_Create) isCustomerClientLinkOperation_Operation() {}

func (*CustomerClientLinkOperation_Update) isCustomerClientLinkOperation_Operation() {}

// Response message for a CustomerClientLink mutate.
type MutateCustomerClientLinkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A result that identifies the resource affected by the mutate request.
	Result        *MutateCustomerClientLinkResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateCustomerClientLinkResponse) Reset() {
	*x = MutateCustomerClientLinkResponse{}
	mi := &file_google_ads_googleads_v20_services_customer_client_link_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateCustomerClientLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateCustomerClientLinkResponse) ProtoMessage() {}

func (x *MutateCustomerClientLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_customer_client_link_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateCustomerClientLinkResponse.ProtoReflect.Descriptor instead.
func (*MutateCustomerClientLinkResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDescGZIP(), []int{2}
}

func (x *MutateCustomerClientLinkResponse) GetResult() *MutateCustomerClientLinkResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// The result for a single customer client link mutate.
type MutateCustomerClientLinkResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returned for successful operations.
	ResourceName  string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateCustomerClientLinkResult) Reset() {
	*x = MutateCustomerClientLinkResult{}
	mi := &file_google_ads_googleads_v20_services_customer_client_link_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateCustomerClientLinkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateCustomerClientLinkResult) ProtoMessage() {}

func (x *MutateCustomerClientLinkResult) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_customer_client_link_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateCustomerClientLinkResult.ProtoReflect.Descriptor instead.
func (*MutateCustomerClientLinkResult) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDescGZIP(), []int{3}
}

func (x *MutateCustomerClientLinkResult) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

var File_google_ads_googleads_v20_services_customer_client_link_service_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDesc = "" +
	"\n" +
	"Dgoogle/ads/googleads/v20/services/customer_client_link_service.proto\x12!google.ads.googleads.v20.services\x1a=google/ads/googleads/v20/resources/customer_client_link.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\"\xcf\x01\n" +
	"\x1fMutateCustomerClientLinkRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12a\n" +
	"\toperation\x18\x02 \x01(\v2>.google.ads.googleads.v20.services.CustomerClientLinkOperationB\x03\xe0A\x02R\toperation\x12#\n" +
	"\rvalidate_only\x18\x03 \x01(\bR\fvalidateOnly\"\x8b\x02\n" +
	"\x1bCustomerClientLinkOperation\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12P\n" +
	"\x06create\x18\x01 \x01(\v26.google.ads.googleads.v20.resources.CustomerClientLinkH\x00R\x06create\x12P\n" +
	"\x06update\x18\x02 \x01(\v26.google.ads.googleads.v20.resources.CustomerClientLinkH\x00R\x06updateB\v\n" +
	"\toperation\"}\n" +
	" MutateCustomerClientLinkResponse\x12Y\n" +
	"\x06result\x18\x01 \x01(\v2A.google.ads.googleads.v20.services.MutateCustomerClientLinkResultR\x06result\"w\n" +
	"\x1eMutateCustomerClientLinkResult\x12U\n" +
	"\rresource_name\x18\x01 \x01(\tB0\xfaA-\n" +
	"+googleads.googleapis.com/CustomerClientLinkR\fresourceName2\xe6\x02\n" +
	"\x19CustomerClientLinkService\x12\x81\x02\n" +
	"\x18MutateCustomerClientLink\x12B.google.ads.googleads.v20.services.MutateCustomerClientLinkRequest\x1aC.google.ads.googleads.v20.services.MutateCustomerClientLinkResponse\"\\\xdaA\x15customer_id,operation\x82\xd3\xe4\x93\x02>:\x01*\"9/v20/customers/{customer_id=*}/customerClientLinks:mutate\x1aE\xcaA\x18googleads.googleapis.com\xd2A'https://www.googleapis.com/auth/adwordsB\x8a\x02\n" +
	"%com.google.ads.googleads.v20.servicesB\x1eCustomerClientLinkServiceProtoP\x01ZIgithub.com/shenzhencenter/google-ads-pb/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V20.Services\xca\x02!Google\\Ads\\GoogleAds\\V20\\Services\xea\x02%Google::Ads::GoogleAds::V20::Servicesb\x06proto3"

var (
	file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDescData []byte
)

func file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDesc), len(file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDesc)))
	})
	return file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDescData
}

var file_google_ads_googleads_v20_services_customer_client_link_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_google_ads_googleads_v20_services_customer_client_link_service_proto_goTypes = []any{
	(*MutateCustomerClientLinkRequest)(nil),  // 0: google.ads.googleads.v20.services.MutateCustomerClientLinkRequest
	(*CustomerClientLinkOperation)(nil),      // 1: google.ads.googleads.v20.services.CustomerClientLinkOperation
	(*MutateCustomerClientLinkResponse)(nil), // 2: google.ads.googleads.v20.services.MutateCustomerClientLinkResponse
	(*MutateCustomerClientLinkResult)(nil),   // 3: google.ads.googleads.v20.services.MutateCustomerClientLinkResult
	(*fieldmaskpb.FieldMask)(nil),            // 4: google.protobuf.FieldMask
	(*resources.CustomerClientLink)(nil),     // 5: google.ads.googleads.v20.resources.CustomerClientLink
}
var file_google_ads_googleads_v20_services_customer_client_link_service_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v20.services.MutateCustomerClientLinkRequest.operation:type_name -> google.ads.googleads.v20.services.CustomerClientLinkOperation
	4, // 1: google.ads.googleads.v20.services.CustomerClientLinkOperation.update_mask:type_name -> google.protobuf.FieldMask
	5, // 2: google.ads.googleads.v20.services.CustomerClientLinkOperation.create:type_name -> google.ads.googleads.v20.resources.CustomerClientLink
	5, // 3: google.ads.googleads.v20.services.CustomerClientLinkOperation.update:type_name -> google.ads.googleads.v20.resources.CustomerClientLink
	3, // 4: google.ads.googleads.v20.services.MutateCustomerClientLinkResponse.result:type_name -> google.ads.googleads.v20.services.MutateCustomerClientLinkResult
	0, // 5: google.ads.googleads.v20.services.CustomerClientLinkService.MutateCustomerClientLink:input_type -> google.ads.googleads.v20.services.MutateCustomerClientLinkRequest
	2, // 6: google.ads.googleads.v20.services.CustomerClientLinkService.MutateCustomerClientLink:output_type -> google.ads.googleads.v20.services.MutateCustomerClientLinkResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v20_services_customer_client_link_service_proto_init() }
func file_google_ads_googleads_v20_services_customer_client_link_service_proto_init() {
	if File_google_ads_googleads_v20_services_customer_client_link_service_proto != nil {
		return
	}
	file_google_ads_googleads_v20_services_customer_client_link_service_proto_msgTypes[1].OneofWrappers = []any{
		(*CustomerClientLinkOperation_Create)(nil),
		(*CustomerClientLinkOperation_Update)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDesc), len(file_google_ads_googleads_v20_services_customer_client_link_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_ads_googleads_v20_services_customer_client_link_service_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v20_services_customer_client_link_service_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v20_services_customer_client_link_service_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v20_services_customer_client_link_service_proto = out.File
	file_google_ads_googleads_v20_services_customer_client_link_service_proto_goTypes = nil
	file_google_ads_googleads_v20_services_customer_client_link_service_proto_depIdxs = nil
}
