// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: google/ads/googleads/v19/errors/date_error.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing possible date errors.
type DateErrorEnum_DateError int32

const (
	// Enum unspecified.
	DateErrorEnum_UNSPECIFIED DateErrorEnum_DateError = 0
	// The received error code is not known in this version.
	DateErrorEnum_UNKNOWN DateErrorEnum_DateError = 1
	// Given field values do not correspond to a valid date.
	DateErrorEnum_INVALID_FIELD_VALUES_IN_DATE DateErrorEnum_DateError = 2
	// Given field values do not correspond to a valid date time.
	DateErrorEnum_INVALID_FIELD_VALUES_IN_DATE_TIME DateErrorEnum_DateError = 3
	// The string date's format should be yyyy-mm-dd.
	DateErrorEnum_INVALID_STRING_DATE DateErrorEnum_DateError = 4
	// The string date time's format should be yyyy-mm-dd hh:mm:ss.ssssss.
	DateErrorEnum_INVALID_STRING_DATE_TIME_MICROS DateErrorEnum_DateError = 6
	// The string date time's format should be yyyy-mm-dd hh:mm:ss.
	DateErrorEnum_INVALID_STRING_DATE_TIME_SECONDS DateErrorEnum_DateError = 11
	// The string date time's format should be yyyy-mm-dd hh:mm:ss+|-hh:mm.
	DateErrorEnum_INVALID_STRING_DATE_TIME_SECONDS_WITH_OFFSET DateErrorEnum_DateError = 12
	// Date is before allowed minimum.
	DateErrorEnum_EARLIER_THAN_MINIMUM_DATE DateErrorEnum_DateError = 7
	// Date is after allowed maximum.
	DateErrorEnum_LATER_THAN_MAXIMUM_DATE DateErrorEnum_DateError = 8
	// Date range bounds are not in order.
	DateErrorEnum_DATE_RANGE_MINIMUM_DATE_LATER_THAN_MAXIMUM_DATE DateErrorEnum_DateError = 9
	// Both dates in range are null.
	DateErrorEnum_DATE_RANGE_MINIMUM_AND_MAXIMUM_DATES_BOTH_NULL DateErrorEnum_DateError = 10
)

// Enum value maps for DateErrorEnum_DateError.
var (
	DateErrorEnum_DateError_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "UNKNOWN",
		2:  "INVALID_FIELD_VALUES_IN_DATE",
		3:  "INVALID_FIELD_VALUES_IN_DATE_TIME",
		4:  "INVALID_STRING_DATE",
		6:  "INVALID_STRING_DATE_TIME_MICROS",
		11: "INVALID_STRING_DATE_TIME_SECONDS",
		12: "INVALID_STRING_DATE_TIME_SECONDS_WITH_OFFSET",
		7:  "EARLIER_THAN_MINIMUM_DATE",
		8:  "LATER_THAN_MAXIMUM_DATE",
		9:  "DATE_RANGE_MINIMUM_DATE_LATER_THAN_MAXIMUM_DATE",
		10: "DATE_RANGE_MINIMUM_AND_MAXIMUM_DATES_BOTH_NULL",
	}
	DateErrorEnum_DateError_value = map[string]int32{
		"UNSPECIFIED":                                     0,
		"UNKNOWN":                                         1,
		"INVALID_FIELD_VALUES_IN_DATE":                    2,
		"INVALID_FIELD_VALUES_IN_DATE_TIME":               3,
		"INVALID_STRING_DATE":                             4,
		"INVALID_STRING_DATE_TIME_MICROS":                 6,
		"INVALID_STRING_DATE_TIME_SECONDS":                11,
		"INVALID_STRING_DATE_TIME_SECONDS_WITH_OFFSET":    12,
		"EARLIER_THAN_MINIMUM_DATE":                       7,
		"LATER_THAN_MAXIMUM_DATE":                         8,
		"DATE_RANGE_MINIMUM_DATE_LATER_THAN_MAXIMUM_DATE": 9,
		"DATE_RANGE_MINIMUM_AND_MAXIMUM_DATES_BOTH_NULL":  10,
	}
)

func (x DateErrorEnum_DateError) Enum() *DateErrorEnum_DateError {
	p := new(DateErrorEnum_DateError)
	*p = x
	return p
}

func (x DateErrorEnum_DateError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DateErrorEnum_DateError) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v19_errors_date_error_proto_enumTypes[0].Descriptor()
}

func (DateErrorEnum_DateError) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v19_errors_date_error_proto_enumTypes[0]
}

func (x DateErrorEnum_DateError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DateErrorEnum_DateError.Descriptor instead.
func (DateErrorEnum_DateError) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v19_errors_date_error_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing possible date errors.
type DateErrorEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateErrorEnum) Reset() {
	*x = DateErrorEnum{}
	mi := &file_google_ads_googleads_v19_errors_date_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateErrorEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateErrorEnum) ProtoMessage() {}

func (x *DateErrorEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v19_errors_date_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateErrorEnum.ProtoReflect.Descriptor instead.
func (*DateErrorEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v19_errors_date_error_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v19_errors_date_error_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v19_errors_date_error_proto_rawDesc = "" +
	"\n" +
	"0google/ads/googleads/v19/errors/date_error.proto\x12\x1fgoogle.ads.googleads.v19.errors\"\xbf\x03\n" +
	"\rDateErrorEnum\"\xad\x03\n" +
	"\tDateError\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12 \n" +
	"\x1cINVALID_FIELD_VALUES_IN_DATE\x10\x02\x12%\n" +
	"!INVALID_FIELD_VALUES_IN_DATE_TIME\x10\x03\x12\x17\n" +
	"\x13INVALID_STRING_DATE\x10\x04\x12#\n" +
	"\x1fINVALID_STRING_DATE_TIME_MICROS\x10\x06\x12$\n" +
	" INVALID_STRING_DATE_TIME_SECONDS\x10\v\x120\n" +
	",INVALID_STRING_DATE_TIME_SECONDS_WITH_OFFSET\x10\f\x12\x1d\n" +
	"\x19EARLIER_THAN_MINIMUM_DATE\x10\a\x12\x1b\n" +
	"\x17LATER_THAN_MAXIMUM_DATE\x10\b\x123\n" +
	"/DATE_RANGE_MINIMUM_DATE_LATER_THAN_MAXIMUM_DATE\x10\t\x122\n" +
	".DATE_RANGE_MINIMUM_AND_MAXIMUM_DATES_BOTH_NULL\x10\n" +
	"B\xee\x01\n" +
	"#com.google.ads.googleads.v19.errorsB\x0eDateErrorProtoP\x01ZEgithub.com/shenzhencenter/google-ads-pb/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V19.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V19\\Errors\xea\x02#Google::Ads::GoogleAds::V19::Errorsb\x06proto3"

var (
	file_google_ads_googleads_v19_errors_date_error_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v19_errors_date_error_proto_rawDescData []byte
)

func file_google_ads_googleads_v19_errors_date_error_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v19_errors_date_error_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v19_errors_date_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_errors_date_error_proto_rawDesc), len(file_google_ads_googleads_v19_errors_date_error_proto_rawDesc)))
	})
	return file_google_ads_googleads_v19_errors_date_error_proto_rawDescData
}

var file_google_ads_googleads_v19_errors_date_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v19_errors_date_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v19_errors_date_error_proto_goTypes = []any{
	(DateErrorEnum_DateError)(0), // 0: google.ads.googleads.v19.errors.DateErrorEnum.DateError
	(*DateErrorEnum)(nil),        // 1: google.ads.googleads.v19.errors.DateErrorEnum
}
var file_google_ads_googleads_v19_errors_date_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v19_errors_date_error_proto_init() }
func file_google_ads_googleads_v19_errors_date_error_proto_init() {
	if File_google_ads_googleads_v19_errors_date_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_errors_date_error_proto_rawDesc), len(file_google_ads_googleads_v19_errors_date_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v19_errors_date_error_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v19_errors_date_error_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v19_errors_date_error_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v19_errors_date_error_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v19_errors_date_error_proto = out.File
	file_google_ads_googleads_v19_errors_date_error_proto_goTypes = nil
	file_google_ads_googleads_v19_errors_date_error_proto_depIdxs = nil
}
