// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: google/ads/googleads/v20/errors/feed_item_target_error.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing possible feed item target errors.
type FeedItemTargetErrorEnum_FeedItemTargetError int32

const (
	// Enum unspecified.
	FeedItemTargetErrorEnum_UNSPECIFIED FeedItemTargetErrorEnum_FeedItemTargetError = 0
	// The received error code is not known in this version.
	FeedItemTargetErrorEnum_UNKNOWN FeedItemTargetErrorEnum_FeedItemTargetError = 1
	// On CREATE, the FeedItemTarget must have a populated field in the oneof
	// target.
	FeedItemTargetErrorEnum_MUST_SET_TARGET_ONEOF_ON_CREATE FeedItemTargetErrorEnum_FeedItemTargetError = 2
	// The specified feed item target already exists, so it cannot be added.
	FeedItemTargetErrorEnum_FEED_ITEM_TARGET_ALREADY_EXISTS FeedItemTargetErrorEnum_FeedItemTargetError = 3
	// The schedules for a given feed item cannot overlap.
	FeedItemTargetErrorEnum_FEED_ITEM_SCHEDULES_CANNOT_OVERLAP FeedItemTargetErrorEnum_FeedItemTargetError = 4
	// Too many targets of a given type were added for a single feed item.
	FeedItemTargetErrorEnum_TARGET_LIMIT_EXCEEDED_FOR_GIVEN_TYPE FeedItemTargetErrorEnum_FeedItemTargetError = 5
	// Too many AdSchedules are enabled for the feed item for the given day.
	FeedItemTargetErrorEnum_TOO_MANY_SCHEDULES_PER_DAY FeedItemTargetErrorEnum_FeedItemTargetError = 6
	// A feed item may either have an enabled campaign target or an enabled ad
	// group target.
	FeedItemTargetErrorEnum_CANNOT_HAVE_ENABLED_CAMPAIGN_AND_ENABLED_AD_GROUP_TARGETS FeedItemTargetErrorEnum_FeedItemTargetError = 7
	// Duplicate ad schedules aren't allowed.
	FeedItemTargetErrorEnum_DUPLICATE_AD_SCHEDULE FeedItemTargetErrorEnum_FeedItemTargetError = 8
	// Duplicate keywords aren't allowed.
	FeedItemTargetErrorEnum_DUPLICATE_KEYWORD FeedItemTargetErrorEnum_FeedItemTargetError = 9
)

// Enum value maps for FeedItemTargetErrorEnum_FeedItemTargetError.
var (
	FeedItemTargetErrorEnum_FeedItemTargetError_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "MUST_SET_TARGET_ONEOF_ON_CREATE",
		3: "FEED_ITEM_TARGET_ALREADY_EXISTS",
		4: "FEED_ITEM_SCHEDULES_CANNOT_OVERLAP",
		5: "TARGET_LIMIT_EXCEEDED_FOR_GIVEN_TYPE",
		6: "TOO_MANY_SCHEDULES_PER_DAY",
		7: "CANNOT_HAVE_ENABLED_CAMPAIGN_AND_ENABLED_AD_GROUP_TARGETS",
		8: "DUPLICATE_AD_SCHEDULE",
		9: "DUPLICATE_KEYWORD",
	}
	FeedItemTargetErrorEnum_FeedItemTargetError_value = map[string]int32{
		"UNSPECIFIED":                                               0,
		"UNKNOWN":                                                   1,
		"MUST_SET_TARGET_ONEOF_ON_CREATE":                           2,
		"FEED_ITEM_TARGET_ALREADY_EXISTS":                           3,
		"FEED_ITEM_SCHEDULES_CANNOT_OVERLAP":                        4,
		"TARGET_LIMIT_EXCEEDED_FOR_GIVEN_TYPE":                      5,
		"TOO_MANY_SCHEDULES_PER_DAY":                                6,
		"CANNOT_HAVE_ENABLED_CAMPAIGN_AND_ENABLED_AD_GROUP_TARGETS": 7,
		"DUPLICATE_AD_SCHEDULE":                                     8,
		"DUPLICATE_KEYWORD":                                         9,
	}
)

func (x FeedItemTargetErrorEnum_FeedItemTargetError) Enum() *FeedItemTargetErrorEnum_FeedItemTargetError {
	p := new(FeedItemTargetErrorEnum_FeedItemTargetError)
	*p = x
	return p
}

func (x FeedItemTargetErrorEnum_FeedItemTargetError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedItemTargetErrorEnum_FeedItemTargetError) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v20_errors_feed_item_target_error_proto_enumTypes[0].Descriptor()
}

func (FeedItemTargetErrorEnum_FeedItemTargetError) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v20_errors_feed_item_target_error_proto_enumTypes[0]
}

func (x FeedItemTargetErrorEnum_FeedItemTargetError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedItemTargetErrorEnum_FeedItemTargetError.Descriptor instead.
func (FeedItemTargetErrorEnum_FeedItemTargetError) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing possible feed item target errors.
type FeedItemTargetErrorEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItemTargetErrorEnum) Reset() {
	*x = FeedItemTargetErrorEnum{}
	mi := &file_google_ads_googleads_v20_errors_feed_item_target_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItemTargetErrorEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItemTargetErrorEnum) ProtoMessage() {}

func (x *FeedItemTargetErrorEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_errors_feed_item_target_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItemTargetErrorEnum.ProtoReflect.Descriptor instead.
func (*FeedItemTargetErrorEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v20_errors_feed_item_target_error_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDesc = "" +
	"\n" +
	"<google/ads/googleads/v20/errors/feed_item_target_error.proto\x12\x1fgoogle.ads.googleads.v20.errors\"\xfc\x02\n" +
	"\x17FeedItemTargetErrorEnum\"\xe0\x02\n" +
	"\x13FeedItemTargetError\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12#\n" +
	"\x1fMUST_SET_TARGET_ONEOF_ON_CREATE\x10\x02\x12#\n" +
	"\x1fFEED_ITEM_TARGET_ALREADY_EXISTS\x10\x03\x12&\n" +
	"\"FEED_ITEM_SCHEDULES_CANNOT_OVERLAP\x10\x04\x12(\n" +
	"$TARGET_LIMIT_EXCEEDED_FOR_GIVEN_TYPE\x10\x05\x12\x1e\n" +
	"\x1aTOO_MANY_SCHEDULES_PER_DAY\x10\x06\x12=\n" +
	"9CANNOT_HAVE_ENABLED_CAMPAIGN_AND_ENABLED_AD_GROUP_TARGETS\x10\a\x12\x19\n" +
	"\x15DUPLICATE_AD_SCHEDULE\x10\b\x12\x15\n" +
	"\x11DUPLICATE_KEYWORD\x10\tB\xf8\x01\n" +
	"#com.google.ads.googleads.v20.errorsB\x18FeedItemTargetErrorProtoP\x01ZEgithub.com/shenzhencenter/google-ads-pb/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V20.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V20\\Errors\xea\x02#Google::Ads::GoogleAds::V20::Errorsb\x06proto3"

var (
	file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDescData []byte
)

func file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDesc), len(file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDesc)))
	})
	return file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDescData
}

var file_google_ads_googleads_v20_errors_feed_item_target_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v20_errors_feed_item_target_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v20_errors_feed_item_target_error_proto_goTypes = []any{
	(FeedItemTargetErrorEnum_FeedItemTargetError)(0), // 0: google.ads.googleads.v20.errors.FeedItemTargetErrorEnum.FeedItemTargetError
	(*FeedItemTargetErrorEnum)(nil),                  // 1: google.ads.googleads.v20.errors.FeedItemTargetErrorEnum
}
var file_google_ads_googleads_v20_errors_feed_item_target_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v20_errors_feed_item_target_error_proto_init() }
func file_google_ads_googleads_v20_errors_feed_item_target_error_proto_init() {
	if File_google_ads_googleads_v20_errors_feed_item_target_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDesc), len(file_google_ads_googleads_v20_errors_feed_item_target_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v20_errors_feed_item_target_error_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v20_errors_feed_item_target_error_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v20_errors_feed_item_target_error_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v20_errors_feed_item_target_error_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v20_errors_feed_item_target_error_proto = out.File
	file_google_ads_googleads_v20_errors_feed_item_target_error_proto_goTypes = nil
	file_google_ads_googleads_v20_errors_feed_item_target_error_proto_depIdxs = nil
}
