// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: google/ads/googleads/v20/errors/invoice_error.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing possible invoice errors.
type InvoiceErrorEnum_InvoiceError int32

const (
	// Enum unspecified.
	InvoiceErrorEnum_UNSPECIFIED InvoiceErrorEnum_InvoiceError = 0
	// The received error code is not known in this version.
	InvoiceErrorEnum_UNKNOWN InvoiceErrorEnum_InvoiceError = 1
	// Cannot request invoices issued before 2019-01-01.
	InvoiceErrorEnum_YEAR_MONTH_TOO_OLD InvoiceErrorEnum_InvoiceError = 2
	// Cannot request invoices for customer who doesn't receive invoices.
	InvoiceErrorEnum_NOT_INVOICED_CUSTOMER InvoiceErrorEnum_InvoiceError = 3
	// Cannot request invoices for a non approved billing setup.
	InvoiceErrorEnum_BILLING_SETUP_NOT_APPROVED InvoiceErrorEnum_InvoiceError = 4
	// Cannot request invoices for a billing setup that is not on monthly
	// invoicing.
	InvoiceErrorEnum_BILLING_SETUP_NOT_ON_MONTHLY_INVOICING InvoiceErrorEnum_InvoiceError = 5
	// Cannot request invoices for a non serving customer.
	InvoiceErrorEnum_NON_SERVING_CUSTOMER InvoiceErrorEnum_InvoiceError = 6
)

// Enum value maps for InvoiceErrorEnum_InvoiceError.
var (
	InvoiceErrorEnum_InvoiceError_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "YEAR_MONTH_TOO_OLD",
		3: "NOT_INVOICED_CUSTOMER",
		4: "BILLING_SETUP_NOT_APPROVED",
		5: "BILLING_SETUP_NOT_ON_MONTHLY_INVOICING",
		6: "NON_SERVING_CUSTOMER",
	}
	InvoiceErrorEnum_InvoiceError_value = map[string]int32{
		"UNSPECIFIED":                            0,
		"UNKNOWN":                                1,
		"YEAR_MONTH_TOO_OLD":                     2,
		"NOT_INVOICED_CUSTOMER":                  3,
		"BILLING_SETUP_NOT_APPROVED":             4,
		"BILLING_SETUP_NOT_ON_MONTHLY_INVOICING": 5,
		"NON_SERVING_CUSTOMER":                   6,
	}
)

func (x InvoiceErrorEnum_InvoiceError) Enum() *InvoiceErrorEnum_InvoiceError {
	p := new(InvoiceErrorEnum_InvoiceError)
	*p = x
	return p
}

func (x InvoiceErrorEnum_InvoiceError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvoiceErrorEnum_InvoiceError) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v20_errors_invoice_error_proto_enumTypes[0].Descriptor()
}

func (InvoiceErrorEnum_InvoiceError) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v20_errors_invoice_error_proto_enumTypes[0]
}

func (x InvoiceErrorEnum_InvoiceError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvoiceErrorEnum_InvoiceError.Descriptor instead.
func (InvoiceErrorEnum_InvoiceError) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_errors_invoice_error_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing possible invoice errors.
type InvoiceErrorEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceErrorEnum) Reset() {
	*x = InvoiceErrorEnum{}
	mi := &file_google_ads_googleads_v20_errors_invoice_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceErrorEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceErrorEnum) ProtoMessage() {}

func (x *InvoiceErrorEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_errors_invoice_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceErrorEnum.ProtoReflect.Descriptor instead.
func (*InvoiceErrorEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_errors_invoice_error_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v20_errors_invoice_error_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v20_errors_invoice_error_proto_rawDesc = "" +
	"\n" +
	"3google/ads/googleads/v20/errors/invoice_error.proto\x12\x1fgoogle.ads.googleads.v20.errors\"\xda\x01\n" +
	"\x10InvoiceErrorEnum\"\xc5\x01\n" +
	"\fInvoiceError\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\x16\n" +
	"\x12YEAR_MONTH_TOO_OLD\x10\x02\x12\x19\n" +
	"\x15NOT_INVOICED_CUSTOMER\x10\x03\x12\x1e\n" +
	"\x1aBILLING_SETUP_NOT_APPROVED\x10\x04\x12*\n" +
	"&BILLING_SETUP_NOT_ON_MONTHLY_INVOICING\x10\x05\x12\x18\n" +
	"\x14NON_SERVING_CUSTOMER\x10\x06B\xf1\x01\n" +
	"#com.google.ads.googleads.v20.errorsB\x11InvoiceErrorProtoP\x01ZEgithub.com/shenzhencenter/google-ads-pb/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V20.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V20\\Errors\xea\x02#Google::Ads::GoogleAds::V20::Errorsb\x06proto3"

var (
	file_google_ads_googleads_v20_errors_invoice_error_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v20_errors_invoice_error_proto_rawDescData []byte
)

func file_google_ads_googleads_v20_errors_invoice_error_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v20_errors_invoice_error_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v20_errors_invoice_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_errors_invoice_error_proto_rawDesc), len(file_google_ads_googleads_v20_errors_invoice_error_proto_rawDesc)))
	})
	return file_google_ads_googleads_v20_errors_invoice_error_proto_rawDescData
}

var file_google_ads_googleads_v20_errors_invoice_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v20_errors_invoice_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v20_errors_invoice_error_proto_goTypes = []any{
	(InvoiceErrorEnum_InvoiceError)(0), // 0: google.ads.googleads.v20.errors.InvoiceErrorEnum.InvoiceError
	(*InvoiceErrorEnum)(nil),           // 1: google.ads.googleads.v20.errors.InvoiceErrorEnum
}
var file_google_ads_googleads_v20_errors_invoice_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v20_errors_invoice_error_proto_init() }
func file_google_ads_googleads_v20_errors_invoice_error_proto_init() {
	if File_google_ads_googleads_v20_errors_invoice_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_errors_invoice_error_proto_rawDesc), len(file_google_ads_googleads_v20_errors_invoice_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v20_errors_invoice_error_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v20_errors_invoice_error_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v20_errors_invoice_error_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v20_errors_invoice_error_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v20_errors_invoice_error_proto = out.File
	file_google_ads_googleads_v20_errors_invoice_error_proto_goTypes = nil
	file_google_ads_googleads_v20_errors_invoice_error_proto_depIdxs = nil
}
