// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: google/ads/googleads/v19/errors/smart_campaign_error.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing possible Smart campaign errors.
type SmartCampaignErrorEnum_SmartCampaignError int32

const (
	// Enum unspecified.
	SmartCampaignErrorEnum_UNSPECIFIED SmartCampaignErrorEnum_SmartCampaignError = 0
	// The received error code is not known in this version.
	SmartCampaignErrorEnum_UNKNOWN SmartCampaignErrorEnum_SmartCampaignError = 1
	// The business location id is invalid.
	SmartCampaignErrorEnum_INVALID_BUSINESS_LOCATION_ID SmartCampaignErrorEnum_SmartCampaignError = 2
	// The SmartCampaignSetting resource is only applicable for campaigns
	// with advertising channel type SMART.
	SmartCampaignErrorEnum_INVALID_CAMPAIGN SmartCampaignErrorEnum_SmartCampaignError = 3
	// The business name or business location id is required.
	SmartCampaignErrorEnum_BUSINESS_NAME_OR_BUSINESS_LOCATION_ID_MISSING SmartCampaignErrorEnum_SmartCampaignError = 4
	// A Smart campaign suggestion request field is required.
	SmartCampaignErrorEnum_REQUIRED_SUGGESTION_FIELD_MISSING SmartCampaignErrorEnum_SmartCampaignError = 5
	// A location list or proximity is required.
	SmartCampaignErrorEnum_GEO_TARGETS_REQUIRED SmartCampaignErrorEnum_SmartCampaignError = 6
	// The locale could not be determined.
	SmartCampaignErrorEnum_CANNOT_DETERMINE_SUGGESTION_LOCALE SmartCampaignErrorEnum_SmartCampaignError = 7
	// The final URL could not be crawled.
	SmartCampaignErrorEnum_FINAL_URL_NOT_CRAWLABLE SmartCampaignErrorEnum_SmartCampaignError = 8
)

// Enum value maps for SmartCampaignErrorEnum_SmartCampaignError.
var (
	SmartCampaignErrorEnum_SmartCampaignError_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "INVALID_BUSINESS_LOCATION_ID",
		3: "INVALID_CAMPAIGN",
		4: "BUSINESS_NAME_OR_BUSINESS_LOCATION_ID_MISSING",
		5: "REQUIRED_SUGGESTION_FIELD_MISSING",
		6: "GEO_TARGETS_REQUIRED",
		7: "CANNOT_DETERMINE_SUGGESTION_LOCALE",
		8: "FINAL_URL_NOT_CRAWLABLE",
	}
	SmartCampaignErrorEnum_SmartCampaignError_value = map[string]int32{
		"UNSPECIFIED":                  0,
		"UNKNOWN":                      1,
		"INVALID_BUSINESS_LOCATION_ID": 2,
		"INVALID_CAMPAIGN":             3,
		"BUSINESS_NAME_OR_BUSINESS_LOCATION_ID_MISSING": 4,
		"REQUIRED_SUGGESTION_FIELD_MISSING":             5,
		"GEO_TARGETS_REQUIRED":                          6,
		"CANNOT_DETERMINE_SUGGESTION_LOCALE":            7,
		"FINAL_URL_NOT_CRAWLABLE":                       8,
	}
)

func (x SmartCampaignErrorEnum_SmartCampaignError) Enum() *SmartCampaignErrorEnum_SmartCampaignError {
	p := new(SmartCampaignErrorEnum_SmartCampaignError)
	*p = x
	return p
}

func (x SmartCampaignErrorEnum_SmartCampaignError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmartCampaignErrorEnum_SmartCampaignError) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v19_errors_smart_campaign_error_proto_enumTypes[0].Descriptor()
}

func (SmartCampaignErrorEnum_SmartCampaignError) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v19_errors_smart_campaign_error_proto_enumTypes[0]
}

func (x SmartCampaignErrorEnum_SmartCampaignError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmartCampaignErrorEnum_SmartCampaignError.Descriptor instead.
func (SmartCampaignErrorEnum_SmartCampaignError) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing possible Smart campaign errors.
type SmartCampaignErrorEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmartCampaignErrorEnum) Reset() {
	*x = SmartCampaignErrorEnum{}
	mi := &file_google_ads_googleads_v19_errors_smart_campaign_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmartCampaignErrorEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartCampaignErrorEnum) ProtoMessage() {}

func (x *SmartCampaignErrorEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v19_errors_smart_campaign_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartCampaignErrorEnum.ProtoReflect.Descriptor instead.
func (*SmartCampaignErrorEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v19_errors_smart_campaign_error_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDesc = "" +
	"\n" +
	":google/ads/googleads/v19/errors/smart_campaign_error.proto\x12\x1fgoogle.ads.googleads.v19.errors\"\xbe\x02\n" +
	"\x16SmartCampaignErrorEnum\"\xa3\x02\n" +
	"\x12SmartCampaignError\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12 \n" +
	"\x1cINVALID_BUSINESS_LOCATION_ID\x10\x02\x12\x14\n" +
	"\x10INVALID_CAMPAIGN\x10\x03\x121\n" +
	"-BUSINESS_NAME_OR_BUSINESS_LOCATION_ID_MISSING\x10\x04\x12%\n" +
	"!REQUIRED_SUGGESTION_FIELD_MISSING\x10\x05\x12\x18\n" +
	"\x14GEO_TARGETS_REQUIRED\x10\x06\x12&\n" +
	"\"CANNOT_DETERMINE_SUGGESTION_LOCALE\x10\a\x12\x1b\n" +
	"\x17FINAL_URL_NOT_CRAWLABLE\x10\bB\xf7\x01\n" +
	"#com.google.ads.googleads.v19.errorsB\x17SmartCampaignErrorProtoP\x01ZEgithub.com/shenzhencenter/google-ads-pb/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V19.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V19\\Errors\xea\x02#Google::Ads::GoogleAds::V19::Errorsb\x06proto3"

var (
	file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDescData []byte
)

func file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDesc), len(file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDesc)))
	})
	return file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDescData
}

var file_google_ads_googleads_v19_errors_smart_campaign_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v19_errors_smart_campaign_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v19_errors_smart_campaign_error_proto_goTypes = []any{
	(SmartCampaignErrorEnum_SmartCampaignError)(0), // 0: google.ads.googleads.v19.errors.SmartCampaignErrorEnum.SmartCampaignError
	(*SmartCampaignErrorEnum)(nil),                 // 1: google.ads.googleads.v19.errors.SmartCampaignErrorEnum
}
var file_google_ads_googleads_v19_errors_smart_campaign_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v19_errors_smart_campaign_error_proto_init() }
func file_google_ads_googleads_v19_errors_smart_campaign_error_proto_init() {
	if File_google_ads_googleads_v19_errors_smart_campaign_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDesc), len(file_google_ads_googleads_v19_errors_smart_campaign_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v19_errors_smart_campaign_error_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v19_errors_smart_campaign_error_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v19_errors_smart_campaign_error_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v19_errors_smart_campaign_error_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v19_errors_smart_campaign_error_proto = out.File
	file_google_ads_googleads_v19_errors_smart_campaign_error_proto_goTypes = nil
	file_google_ads_googleads_v19_errors_smart_campaign_error_proto_depIdxs = nil
}
